name: "Check Tags"
description: "Check git tag and npm version for a repository to prevent wrong publications."
inputs:
  npmPackageName: # id of input
    description: "The npm package to get the latest version from the npm registry."
    required: false
    default: "@dlr-eoc/core-ui"
  npmPackageTags:
    description: "The latest Versions of the npm package separated by comma. Use either this or npmPackageName"
    required: false
  repoPackagePath:
    description: "The path to the package.json in the repository."
    required: false
    default: "./package.json"

runs:
  using: "composite"
  steps:
    - run: git fetch --prune --all --tags -f
      shell: bash

    # https://github.com/actions/runner/issues/665
    - run: ${{ github.action_path }}/index.sh
      shell: bash
      env:
        PACKAGE_PATH: ${{ inputs.repoPackagePath }}
        NPM_PACKAGE_NAME: ${{ inputs.npmPackageName }}
        NPM_PACKAGE_TAGS: ${{ inputs.npmPackageTags }}
