name: "Check Tag on Npm"
description: "Check if the tag is already published on npm"
inputs:
  npmPackageName: # id of input
    description: "The npm package to get the latest version from the npm registry."
    required: false
    default: "@dlr-eoc/core-ui"
  npmPackageTags:
    description: "A List of tags. Use this instead of npmPackageName if you can't get the tags from the package."
    required: false
  tag:
    description: "The Tag which should be published on npm"
    required: true

runs:
  using: "composite"
  steps:
    - run: git fetch --prune --all --tags -f
      shell: bash

    # https://github.com/actions/runner/issues/665
    - run: ${{ github.action_path }}/index.sh
      shell: bash
      env:
        NPM_PACKAGE_NAME: ${{ inputs.npmPackageName }}
        NPM_PACKAGE_TAGS: ${{ inputs.npmPackageTags }}
        TAG: ${{ inputs.tag }}
