/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpPurlOrgDcElements11 =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "identifier";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "relation";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "format";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "title";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "description";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "source";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "date";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "type";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "language";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "DC-element";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "rights";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "creator";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "publisher";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "contributor";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "subject";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "coverage";
        namespaceURI?: "http://purl.org/dc/elements/1.1/";
        [k: string]: unknown;
      };
      value?: SimpleLiteral;
      [k: string]: unknown;
    };
export type Content = (string | null)[];
export type Scheme = string | null;

export interface SimpleLiteral {
  content?: Content;
  scheme?: Scheme;
  [k: string]: unknown;
}
