/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "polygonMember";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PolygonMember;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "featureMember";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: FeatureMember;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "property";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Property;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Box";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Box;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "boundedBy";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: BoundedBy;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "MultiPolygon";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiPolygon;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LineString";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LineString;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiLineStringProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiLineStringProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiExtentOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiExtentOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "innerBoundaryIs";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: InnerBoundaryIs;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiCoverage";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiCoverage;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "polygonProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PolygonProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "geometryMember";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GeometryMember;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiLocation";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiLocation;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "extentOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ExtentOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "coverage";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Coverage;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "outerBoundaryIs";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: OuterBoundaryIs;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "geometryCollectionProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GeometryCollectionProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "position";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Position;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiEdgeOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiEdgeOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "pointProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PointProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Point";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Point;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "location";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Location;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "edgeOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: EdgeOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiPolygonProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiPolygonProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiPosition";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiPosition;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "centerLineOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: CenterLineOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "MultiPoint";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiPoint;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LinearRing";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LinearRing;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Feature";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Feature;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiCenterOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiCenterOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "geometricProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GeometricProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiPointProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiPointProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "centerOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: CenterOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "multiCenterLineOf";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiCenterLineOf;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "lineStringProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LineStringProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "geometryProperty";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GeometryProperty;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Polygon";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Polygon;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "FeatureCollection";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: FeatureCollection;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "MultiLineString";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MultiLineString;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "coordinates";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Coordinates;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GeometryCollection";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GeometryCollection;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "lineStringMember";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LineStringMember;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "pointMember";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PointMember;
      [k: string]: unknown;
    };
export type Polygon1 = Polygon;
export type Id = string | null;
export type SrsName = string | null;
export type OuterBoundaryIs1 = OuterBoundaryIs;
export type LinearRing1 = LinearRing;
export type Id1 = string | null;
export type Coordinates1 = Coordinates;
export type Decimal = string | null;
export type Cs = string | null;
export type Ts = string | null;
export type Value = string | null;
export type InnerBoundaryIs1 = InnerBoundaryIs[];
export type LinearRing2 = LinearRing;
export type TypeName = string | null;
export type FeatureOrFeatureCollection = (Feature | FeatureCollection)[];
export type TypeName1 = string | null;
export type Identifier = string | null;
export type Description = string | null;
export type Name = string | null;
export type BoundedBy1 = BoundedBy;
export type Box1 = Box;
export type Id2 = string | null;
export type SrsName1 = string | null;
export type Coordinates2 = Coordinates;
export type Property1 = Property[];
export type TypeName2 = string | null;
export type Type = string | null;
export type Value1 = string | null;
export type GeometricProperty1 = GeometricProperty[];
export type TypeName3 = string | null;
export type PointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection1 = (
  | Point
  | LineString
  | Polygon
  | MultiPoint
  | MultiLineString
  | MultiPolygon
  | GeometryCollection
)[];
export type Id3 = string | null;
export type SrsName2 = string | null;
export type Coordinates3 = Coordinates;
export type Id4 = string | null;
export type SrsName3 = string | null;
export type Coordinates4 = Coordinates;
export type Id5 = string | null;
export type SrsName4 = string | null;
export type PointMember1 = PointMember[];
export type Point1 = Point;
export type Id6 = string | null;
export type SrsName5 = string | null;
export type LineStringMember1 = LineStringMember[];
export type LineString1 = LineString;
export type Id7 = string | null;
export type SrsName6 = string | null;
export type PolygonMember1 = PolygonMember[];
export type Id8 = string | null;
export type SrsName7 = string | null;
export type GeometryMember1 = GeometryMember[];
export type PointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection = (
  | Point
  | LineString
  | Polygon
  | MultiPoint
  | MultiLineString
  | MultiPolygon
  | GeometryCollection
)[];
export type TypeName4 = string | null;
export type Identifier1 = string | null;
export type Description1 = string | null;
export type Name1 = string | null;
export type BoundedBy2 = BoundedBy;
export type Property2 = Property[];
export type GeometricProperty2 = GeometricProperty[];
export type FeatureMember1 = FeatureMember[];
export type MultiLineString1 = MultiLineString;
export type MultiPolygon1 = MultiPolygon;
export type MultiPolygon2 = MultiPolygon;
export type Polygon2 = Polygon;
export type MultiPoint1 = MultiPoint;
export type Polygon3 = Polygon;
export type Polygon4 = Polygon;
export type GeometryCollection1 = GeometryCollection;
export type Point2 = Point;
export type MultiLineString2 = MultiLineString;
export type Point3 = Point;
export type Point4 = Point;
export type LineString2 = LineString;
export type MultiPolygon3 = MultiPolygon;
export type MultiPoint2 = MultiPoint;
export type LineString3 = LineString;
export type MultiPoint3 = MultiPoint;
export type MultiPoint4 = MultiPoint;
export type Point5 = Point;
export type MultiLineString3 = MultiLineString;
export type LineString4 = LineString;
export type PointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection2 = (
  | Point
  | LineString
  | Polygon
  | MultiPoint
  | MultiLineString
  | MultiPolygon
  | GeometryCollection
)[];

export interface PolygonMember {
  polygon?: Polygon1;
  [k: string]: unknown;
}
export interface Polygon {
  id?: Id;
  srsName?: SrsName;
  outerBoundaryIs?: OuterBoundaryIs1;
  innerBoundaryIs?: InnerBoundaryIs1;
  [k: string]: unknown;
}
export interface OuterBoundaryIs {
  linearRing?: LinearRing1;
  [k: string]: unknown;
}
export interface LinearRing {
  id?: Id1;
  coordinates?: Coordinates1;
  [k: string]: unknown;
}
export interface Coordinates {
  decimal?: Decimal;
  cs?: Cs;
  ts?: Ts;
  value?: Value;
  [k: string]: unknown;
}
export interface InnerBoundaryIs {
  linearRing?: LinearRing2;
  [k: string]: unknown;
}
export interface FeatureMember {
  typeName?: TypeName;
  featureOrFeatureCollection?: FeatureOrFeatureCollection;
  [k: string]: unknown;
}
export interface Feature {
  typeName?: TypeName1;
  identifier?: Identifier;
  description?: Description;
  name?: Name;
  boundedBy?: BoundedBy1;
  property?: Property1;
  geometricProperty?: GeometricProperty1;
  [k: string]: unknown;
}
export interface BoundedBy {
  box?: Box1;
  [k: string]: unknown;
}
export interface Box {
  id?: Id2;
  srsName?: SrsName1;
  coordinates?: Coordinates2;
  [k: string]: unknown;
}
export interface Property {
  typeName?: TypeName2;
  type?: Type;
  value?: Value1;
  [k: string]: unknown;
}
export interface GeometricProperty {
  typeName?: TypeName3;
  pointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection?: PointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection1;
  [k: string]: unknown;
}
export interface Point {
  id?: Id3;
  srsName?: SrsName2;
  coordinates?: Coordinates3;
  [k: string]: unknown;
}
export interface LineString {
  id?: Id4;
  srsName?: SrsName3;
  coordinates?: Coordinates4;
  [k: string]: unknown;
}
export interface MultiPoint {
  id?: Id5;
  srsName?: SrsName4;
  pointMember?: PointMember1;
  [k: string]: unknown;
}
export interface PointMember {
  point?: Point1;
  [k: string]: unknown;
}
export interface MultiLineString {
  id?: Id6;
  srsName?: SrsName5;
  lineStringMember?: LineStringMember1;
  [k: string]: unknown;
}
export interface LineStringMember {
  lineString?: LineString1;
  [k: string]: unknown;
}
export interface MultiPolygon {
  id?: Id7;
  srsName?: SrsName6;
  polygonMember?: PolygonMember1;
  [k: string]: unknown;
}
export interface GeometryCollection {
  id?: Id8;
  srsName?: SrsName7;
  geometryMember?: GeometryMember1;
  [k: string]: unknown;
}
export interface GeometryMember {
  pointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection?: PointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection;
  [k: string]: unknown;
}
export interface FeatureCollection {
  typeName?: TypeName4;
  identifier?: Identifier1;
  description?: Description1;
  name?: Name1;
  boundedBy?: BoundedBy2;
  property?: Property2;
  geometricProperty?: GeometricProperty2;
  featureMember?: FeatureMember1;
  [k: string]: unknown;
}
export interface MultiLineStringProperty {
  multiLineString?: MultiLineString1;
  [k: string]: unknown;
}
export interface MultiExtentOf {
  multiPolygon?: MultiPolygon1;
  [k: string]: unknown;
}
export interface MultiCoverage {
  multiPolygon?: MultiPolygon2;
  [k: string]: unknown;
}
export interface PolygonProperty {
  polygon?: Polygon2;
  [k: string]: unknown;
}
export interface MultiLocation {
  multiPoint?: MultiPoint1;
  [k: string]: unknown;
}
export interface ExtentOf {
  polygon?: Polygon3;
  [k: string]: unknown;
}
export interface Coverage {
  polygon?: Polygon4;
  [k: string]: unknown;
}
export interface GeometryCollectionProperty {
  geometryCollection?: GeometryCollection1;
  [k: string]: unknown;
}
export interface Position {
  point?: Point2;
  [k: string]: unknown;
}
export interface MultiEdgeOf {
  multiLineString?: MultiLineString2;
  [k: string]: unknown;
}
export interface PointProperty {
  point?: Point3;
  [k: string]: unknown;
}
export interface Location {
  point?: Point4;
  [k: string]: unknown;
}
export interface EdgeOf {
  lineString?: LineString2;
  [k: string]: unknown;
}
export interface MultiPolygonProperty {
  multiPolygon?: MultiPolygon3;
  [k: string]: unknown;
}
export interface MultiPosition {
  multiPoint?: MultiPoint2;
  [k: string]: unknown;
}
export interface CenterLineOf {
  lineString?: LineString3;
  [k: string]: unknown;
}
export interface MultiCenterOf {
  multiPoint?: MultiPoint3;
  [k: string]: unknown;
}
export interface MultiPointProperty {
  multiPoint?: MultiPoint4;
  [k: string]: unknown;
}
export interface CenterOf {
  point?: Point5;
  [k: string]: unknown;
}
export interface MultiCenterLineOf {
  multiLineString?: MultiLineString3;
  [k: string]: unknown;
}
export interface LineStringProperty {
  lineString?: LineString4;
  [k: string]: unknown;
}
export interface GeometryProperty {
  pointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection?: PointOrLineStringOrPolygonOrMultiPointOrMultiLineStringOrMultiPolygonOrGeometryCollection2;
  [k: string]: unknown;
}
