/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetGml33Exr = {
  name?: ({
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null) & {
    localPart?: "extendedEncodingRule";
    namespaceURI?: "http://www.opengis.net/gml/3.3/exr";
    [k: string]: unknown;
  };
  /**
   * http://www.w3.org/TR/xmlschema-2/#anyURI
   */
  value?: string | null;
  [k: string]: unknown;
};
