/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetGmlcovGeotiff10 = {
  name?: ({
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null) & {
    localPart?: "parameters";
    namespaceURI?: "http://www.opengis.net/gmlcov/geotiff/1.0";
    [k: string]: unknown;
  };
  value?: ParametersType;
  [k: string]: unknown;
};
export type Compression = CompressionType;
export type CompressionType = string | null;
export type JpegQuality = number | null;
export type Predictor = PredictorType;
export type PredictorType = string | null;
export type Interleave = InterleaveType;
export type InterleaveType = string | null;
export type Tiling = boolean | null;
export type Tileheight = number | null;
export type Tilewidth = number | null;

export interface ParametersType {
  compression?: Compression;
  jpegQuality?: JpegQuality;
  predictor?: Predictor;
  interleave?: Interleave;
  tiling?: Tiling;
  tileheight?: Tileheight;
  tilewidth?: Tilewidth;
  [k: string]: unknown;
}
