/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpEarthGoogleComKml21 =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "kml";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: KmlType;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Lod";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LodType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Region";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: RegionType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Orientation";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: OrientationType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "styleUrl";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      /**
       * http://www.w3.org/TR/xmlschema-2/#anyURI
       */
      value?: string | null;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Model";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: ModelType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GroundOverlay";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: GroundOverlayType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Location";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LocationType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "IconStyle";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: IconStyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Feature";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: FeatureType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "coordinates";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: (string | null)[];
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "MultiGeometry";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: MultiGeometryType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "TimeStamp";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: TimeStampType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Link";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LinkType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Style";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: StyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "StyleMap";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: StyleMapType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Icon";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LinkType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Geometry";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: GeometryType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Placemark";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: PlacemarkType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PolyStyle";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: PolyStyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Document";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: DocumentType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LatLonBox";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LatLonBoxType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ListStyle";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: ListStyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Point";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: PointType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LabelStyle";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LabelStyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Polygon";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: PolygonType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LineString";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LineStringType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "state";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: ItemIconStateEnum[];
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "BalloonStyle";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: BalloonStyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Scale";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: ScaleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LatLonAltBox";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LatLonAltBoxType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "TimePrimitive";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: TimePrimitiveType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ScreenOverlay";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: ScreenOverlayType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "TimeSpan";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: TimeSpanType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "NetworkLink";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: NetworkLinkType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "StyleSelector";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: StyleSelectorType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LineStyle";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LineStyleType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LinearRing";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LinearRingType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Object";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: ObjectType;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Folder";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: FolderType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LookAt";
        namespaceURI?: "http://earth.google.com/kml/2.1";
        [k: string]: unknown;
      };
      value?: LookAtType1;
      [k: string]: unknown;
    };
export type NetworkLinkControl = NetworkLinkControlType;
export type MinRefreshPeriod = number | null;
export type Cookie = string | null;
export type Message = string | null;
export type LinkName = string | null;
export type LinkDescription = string | null;
export type LinkSnippet = SnippetType;
export type Value = string | null;
export type MaxLines = number | null;
export type Expires = string | null;
export type Update = UpdateType;
export type TargetHref = string | null;
export type CreateOrDeleteOrChange = (CreateType | DeleteType | ChangeType | ReplaceType)[];
export type Folder = FolderType1;
export type FolderType1 = ContainerType1 & FolderType;
export type ContainerType1 = FeatureType1 & ContainerType;
export type FeatureType1 = ObjectType & FeatureType;
export type Id = string | null;
export type TargetId = string | null;
export type Name = string | null;
export type Visibility = boolean | null;
export type Open = boolean | null;
export type Address = string | null;
export type PhoneNumber = string | null;
export type Snippet = SnippetType;
export type Description = string | null;
export type LookAt = LookAtType1;
export type LookAtType1 = ObjectType & LookAtType;
export type Longitude = number | null;
export type Latitude = number | null;
export type Altitude = number | null;
export type Range = number | null;
export type Tilt = number | null;
export type Heading = number | null;
export type AltitudeMode = AltitudeModeEnum;
export type AltitudeModeEnum = string | null;
export type TimePrimitive = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: TimePrimitiveType1;
  [k: string]: unknown;
};
export type TimePrimitiveType1 = ObjectType & TimePrimitiveType;
export type StyleUrl = string | null;
export type StyleSelector = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: StyleSelectorType1;
  [k: string]: unknown;
}[];
export type StyleSelectorType1 = ObjectType & StyleSelectorType;
export type Region = RegionType1;
export type RegionType1 = ObjectType & RegionType;
export type LatLonAltBox = LatLonAltBoxType1;
export type LatLonAltBoxType1 = LatLonBoxType1 & LatLonAltBoxType;
export type LatLonBoxType1 = ObjectType & LatLonBoxType;
export type North = number | null;
export type South = number | null;
export type East = number | null;
export type West = number | null;
export type Rotation = number | null;
export type MinAltitude = number | null;
export type MaxAltitude = number | null;
export type AltitudeMode1 = AltitudeModeEnum;
export type Lod = LodType1;
export type LodType1 = ObjectType & LodType;
export type MinLodPixels = number | null;
export type MaxLodPixels = number | null;
export type MinFadeExtent = number | null;
export type MaxFadeExtent = number | null;
export type Metadata = MetadataType;
export type Any = unknown;
export type Feature = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: FeatureType1;
  [k: string]: unknown;
}[];
export type Feature1 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: FeatureType1;
  [k: string]: unknown;
}[];
export type ObjectOrFeatureOrGeometry = (
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: StyleSelectorType1;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: FeatureType1;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: TimePrimitiveType1;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: GeometryType1;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ObjectType;
      [k: string]: unknown;
    }
)[];
export type GeometryType1 = ObjectType & GeometryType;
export type Feature2 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: FeatureType1;
  [k: string]: unknown;
};
export type LookAt1 = LookAtType1;
export type Feature3 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: FeatureType1;
  [k: string]: unknown;
};
export type OrientationType1 = ObjectType & OrientationType;
export type Heading1 = number | null;
export type Tilt1 = number | null;
export type Roll = number | null;
export type ModelType1 = GeometryType1 & ModelType;
export type AltitudeMode2 = AltitudeModeEnum;
export type Location = LocationType1;
export type LocationType1 = ObjectType & LocationType;
export type Longitude1 = number | null;
export type Latitude1 = number | null;
export type Altitude1 = number | null;
export type Orientation = OrientationType1;
export type Scale = ScaleType1;
export type ScaleType1 = ObjectType & ScaleType;
export type X = number | null;
export type Y = number | null;
export type Z = number | null;
export type Link = LinkType1;
export type LinkType1 = ObjectType & LinkType;
export type Href = string | null;
export type RefreshMode = RefreshModeEnum;
export type RefreshModeEnum = string | null;
export type RefreshInterval = number | null;
export type ViewRefreshMode = ViewRefreshModeEnum;
export type ViewRefreshModeEnum = string | null;
export type ViewRefreshTime = number | null;
export type ViewBoundScale = number | null;
export type ViewFormat = string | null;
export type HttpQuery = string | null;
export type GroundOverlayType1 = OverlayType1 & GroundOverlayType;
export type OverlayType1 = FeatureType1 & OverlayType;
export type Color = unknown[] | null;
export type DrawOrder = number | null;
export type Icon = LinkType1;
export type Altitude2 = number | null;
export type AltitudeMode3 = AltitudeModeEnum;
export type LatLonBox = LatLonBoxType1;
export type IconStyleType1 = ColorStyleType1 & IconStyleType;
export type ColorStyleType1 = ObjectType & ColorStyleType;
export type Color1 = unknown[] | null;
export type ColorMode = ColorModeEnum;
export type ColorModeEnum = string | null;
export type Scale1 = number | null;
export type Heading2 = number | null;
export type Icon1 = IconStyleIconType1;
export type IconStyleIconType1 = ObjectType & IconStyleIconType;
export type Href1 = string | null;
export type HotSpot = Vec2Type;
export type X1 = number | null;
export type Y1 = number | null;
export type Xunits = UnitsEnum;
export type UnitsEnum = string | null;
export type Yunits = UnitsEnum;
export type MultiGeometryType1 = GeometryType1 & MultiGeometryType;
export type Geometry = [
  {
    /**
     * http://www.w3.org/TR/xmlschema-2/#QName
     */
    name?: {
      namespaceURI?: (string | null) | "";
      /**
       * http://www.w3.org/TR/xmlschema-2/#NCName
       */
      localPart: string | null;
      prefix?: (string | null) | "";
      [k: string]: unknown;
    } | null;
    value?: GeometryType1;
    [k: string]: unknown;
  },
  ...{
    /**
     * http://www.w3.org/TR/xmlschema-2/#QName
     */
    name?: {
      namespaceURI?: (string | null) | "";
      /**
       * http://www.w3.org/TR/xmlschema-2/#NCName
       */
      localPart: string | null;
      prefix?: (string | null) | "";
      [k: string]: unknown;
    } | null;
    value?: GeometryType1;
    [k: string]: unknown;
  }[]
];
export type TimeStampType1 = TimePrimitiveType1 & TimeStampType;
export type When = string | null;
export type StyleType1 = StyleSelectorType1 & StyleType;
export type IconStyle = IconStyleType1;
export type LabelStyle = LabelStyleType1;
export type LabelStyleType1 = ColorStyleType1 & LabelStyleType;
export type Scale2 = number | null;
export type LineStyle = LineStyleType1;
export type LineStyleType1 = ColorStyleType1 & LineStyleType;
export type Width = number | null;
export type PolyStyle = PolyStyleType1;
export type PolyStyleType1 = ColorStyleType1 & PolyStyleType;
export type Fill = boolean | null;
export type Outline = boolean | null;
export type BalloonStyle = BalloonStyleType1;
export type BalloonStyleType1 = ObjectType & BalloonStyleType;
export type Color2 = unknown[] | null;
export type BgColor = unknown[] | null;
export type TextColor = unknown[] | null;
export type Text = string | null;
export type ListStyle = ListStyleType1;
export type ListStyleType1 = ObjectType & ListStyleType;
export type ListItemType = ListItemTypeEnum;
export type ListItemTypeEnum = string | null;
export type BgColor1 = unknown[] | null;
export type ItemIcon = ItemIconType1[];
export type ItemIconType1 = ObjectType & ItemIconType;
export type State = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: ItemIconStateEnum[];
  [k: string]: unknown;
}[];
export type ItemIconStateEnum = string | null;
export type Href2 = string | null;
export type StyleMapType1 = StyleSelectorType1 & StyleMapType;
export type Pair = [StyleMapPairType, ...StyleMapPairType[]];
export type Key = StyleStateEnum;
export type StyleStateEnum = string | null;
export type StyleUrl1 = string | null;
export type PlacemarkType1 = FeatureType1 & PlacemarkType;
export type Geometry1 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: GeometryType1;
  [k: string]: unknown;
};
export type DocumentType1 = ContainerType1 & DocumentType;
export type Feature4 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: FeatureType1;
  [k: string]: unknown;
}[];
export type PointType1 = GeometryType1 & PointType;
export type Extrude = boolean | null;
export type Tessellate = boolean | null;
export type AltitudeMode4 = AltitudeModeEnum;
export type Coordinates = (string | null)[];
export type PolygonType1 = GeometryType1 & PolygonType;
export type Extrude1 = boolean | null;
export type Tessellate1 = boolean | null;
export type AltitudeMode5 = AltitudeModeEnum;
export type OuterBoundaryIs = BoundaryType;
export type LinearRing = LinearRingType1;
export type LinearRingType1 = GeometryType1 & LinearRingType;
export type Extrude2 = boolean | null;
export type Tessellate2 = boolean | null;
export type AltitudeMode6 = AltitudeModeEnum;
export type Coordinates1 = (string | null)[];
export type InnerBoundaryIs = BoundaryType[];
export type LineStringType1 = GeometryType1 & LineStringType;
export type Extrude3 = boolean | null;
export type Tessellate3 = boolean | null;
export type AltitudeMode7 = AltitudeModeEnum;
export type Coordinates2 = (string | null)[];
export type ScreenOverlayType1 = OverlayType1 & ScreenOverlayType;
export type OverlayXY = Vec2Type;
export type ScreenXY = Vec2Type;
export type RotationXY = Vec2Type;
export type Size = Vec2Type;
export type Rotation1 = number | null;
export type TimeSpanType1 = TimePrimitiveType1 & TimeSpanType;
export type Begin = string | null;
export type End = string | null;
export type NetworkLinkType1 = FeatureType1 & NetworkLinkType;
export type RefreshVisibility = boolean | null;
export type FlyToView = boolean | null;
export type Link1 = LinkType1;
export type Url = LinkType1;

export interface KmlType {
  networkLinkControl?: NetworkLinkControl;
  feature?: Feature3;
  [k: string]: unknown;
}
export interface NetworkLinkControlType {
  minRefreshPeriod?: MinRefreshPeriod;
  cookie?: Cookie;
  message?: Message;
  linkName?: LinkName;
  linkDescription?: LinkDescription;
  linkSnippet?: LinkSnippet;
  expires?: Expires;
  update?: Update;
  lookAt?: LookAt1;
  [k: string]: unknown;
}
export interface SnippetType {
  value?: Value;
  maxLines?: MaxLines;
  [k: string]: unknown;
}
export interface UpdateType {
  targetHref: TargetHref;
  createOrDeleteOrChange?: CreateOrDeleteOrChange;
  [k: string]: unknown;
}
export interface CreateType {
  folder: Folder;
  [k: string]: unknown;
}
export interface ObjectType {
  id?: Id;
  targetId?: TargetId;
  [k: string]: unknown;
}
export interface FeatureType {
  name?: Name;
  visibility?: Visibility;
  open?: Open;
  address?: Address;
  phoneNumber?: PhoneNumber;
  snippet?: Snippet;
  description?: Description;
  lookAt?: LookAt;
  timePrimitive?: TimePrimitive;
  styleUrl?: StyleUrl;
  styleSelector?: StyleSelector;
  region?: Region;
  metadata?: Metadata;
  [k: string]: unknown;
}
export interface LookAtType {
  longitude?: Longitude;
  latitude?: Latitude;
  altitude?: Altitude;
  range?: Range;
  tilt?: Tilt;
  heading?: Heading;
  altitudeMode?: AltitudeMode;
  [k: string]: unknown;
}
export interface TimePrimitiveType {
  [k: string]: unknown;
}
export interface StyleSelectorType {
  [k: string]: unknown;
}
export interface RegionType {
  latLonAltBox?: LatLonAltBox;
  lod?: Lod;
  [k: string]: unknown;
}
export interface LatLonBoxType {
  north?: North;
  south?: South;
  east?: East;
  west?: West;
  rotation?: Rotation;
  [k: string]: unknown;
}
export interface LatLonAltBoxType {
  minAltitude?: MinAltitude;
  maxAltitude?: MaxAltitude;
  altitudeMode?: AltitudeMode1;
  [k: string]: unknown;
}
export interface LodType {
  minLodPixels?: MinLodPixels;
  maxLodPixels?: MaxLodPixels;
  minFadeExtent?: MinFadeExtent;
  maxFadeExtent?: MaxFadeExtent;
  [k: string]: unknown;
}
export interface MetadataType {
  any: Any;
  [k: string]: unknown;
}
export interface ContainerType {
  [k: string]: unknown;
}
export interface FolderType {
  feature?: Feature;
  [k: string]: unknown;
}
export interface DeleteType {
  feature?: Feature1;
  [k: string]: unknown;
}
export interface ChangeType {
  objectOrFeatureOrGeometry?: ObjectOrFeatureOrGeometry;
  [k: string]: unknown;
}
export interface GeometryType {
  [k: string]: unknown;
}
export interface ReplaceType {
  feature?: Feature2;
  [k: string]: unknown;
}
export interface OrientationType {
  heading?: Heading1;
  tilt?: Tilt1;
  roll?: Roll;
  [k: string]: unknown;
}
export interface ModelType {
  altitudeMode?: AltitudeMode2;
  location?: Location;
  orientation?: Orientation;
  scale?: Scale;
  link?: Link;
  [k: string]: unknown;
}
export interface LocationType {
  longitude?: Longitude1;
  latitude?: Latitude1;
  altitude?: Altitude1;
  [k: string]: unknown;
}
export interface ScaleType {
  x?: X;
  y?: Y;
  z?: Z;
  [k: string]: unknown;
}
export interface LinkType {
  href?: Href;
  refreshMode?: RefreshMode;
  refreshInterval?: RefreshInterval;
  viewRefreshMode?: ViewRefreshMode;
  viewRefreshTime?: ViewRefreshTime;
  viewBoundScale?: ViewBoundScale;
  viewFormat?: ViewFormat;
  httpQuery?: HttpQuery;
  [k: string]: unknown;
}
export interface OverlayType {
  color?: Color;
  drawOrder?: DrawOrder;
  icon?: Icon;
  [k: string]: unknown;
}
export interface GroundOverlayType {
  altitude?: Altitude2;
  altitudeMode?: AltitudeMode3;
  latLonBox?: LatLonBox;
  [k: string]: unknown;
}
export interface ColorStyleType {
  color?: Color1;
  colorMode?: ColorMode;
  [k: string]: unknown;
}
export interface IconStyleType {
  scale?: Scale1;
  heading?: Heading2;
  icon?: Icon1;
  hotSpot?: HotSpot;
  [k: string]: unknown;
}
export interface IconStyleIconType {
  href?: Href1;
  [k: string]: unknown;
}
export interface Vec2Type {
  x?: X1;
  y?: Y1;
  xunits?: Xunits;
  yunits?: Yunits;
  [k: string]: unknown;
}
export interface MultiGeometryType {
  geometry?: Geometry;
  [k: string]: unknown;
}
export interface TimeStampType {
  when?: When;
  [k: string]: unknown;
}
export interface StyleType {
  iconStyle?: IconStyle;
  labelStyle?: LabelStyle;
  lineStyle?: LineStyle;
  polyStyle?: PolyStyle;
  balloonStyle?: BalloonStyle;
  listStyle?: ListStyle;
  [k: string]: unknown;
}
export interface LabelStyleType {
  scale?: Scale2;
  [k: string]: unknown;
}
export interface LineStyleType {
  width?: Width;
  [k: string]: unknown;
}
export interface PolyStyleType {
  fill?: Fill;
  outline?: Outline;
  [k: string]: unknown;
}
export interface BalloonStyleType {
  color?: Color2;
  bgColor?: BgColor;
  textColor?: TextColor;
  text?: Text;
  [k: string]: unknown;
}
export interface ListStyleType {
  listItemType?: ListItemType;
  bgColor?: BgColor1;
  itemIcon?: ItemIcon;
  [k: string]: unknown;
}
export interface ItemIconType {
  state?: State;
  href?: Href2;
  [k: string]: unknown;
}
export interface StyleMapType {
  pair?: Pair;
  [k: string]: unknown;
}
export interface StyleMapPairType {
  key: Key;
  styleUrl: StyleUrl1;
  [k: string]: unknown;
}
export interface PlacemarkType {
  geometry?: Geometry1;
  [k: string]: unknown;
}
export interface DocumentType {
  feature?: Feature4;
  [k: string]: unknown;
}
export interface PointType {
  extrude?: Extrude;
  tessellate?: Tessellate;
  altitudeMode?: AltitudeMode4;
  coordinates?: Coordinates;
  [k: string]: unknown;
}
export interface PolygonType {
  extrude?: Extrude1;
  tessellate?: Tessellate1;
  altitudeMode?: AltitudeMode5;
  outerBoundaryIs?: OuterBoundaryIs;
  innerBoundaryIs?: InnerBoundaryIs;
  [k: string]: unknown;
}
export interface BoundaryType {
  linearRing: LinearRing;
  [k: string]: unknown;
}
export interface LinearRingType {
  extrude?: Extrude2;
  tessellate?: Tessellate2;
  altitudeMode?: AltitudeMode6;
  coordinates?: Coordinates1;
  [k: string]: unknown;
}
export interface LineStringType {
  extrude?: Extrude3;
  tessellate?: Tessellate3;
  altitudeMode?: AltitudeMode7;
  coordinates?: Coordinates2;
  [k: string]: unknown;
}
export interface ScreenOverlayType {
  overlayXY?: OverlayXY;
  screenXY?: ScreenXY;
  rotationXY?: RotationXY;
  size?: Size;
  rotation?: Rotation1;
  [k: string]: unknown;
}
export interface TimeSpanType {
  begin?: Begin;
  end?: End;
  [k: string]: unknown;
}
export interface NetworkLinkType {
  refreshVisibility?: RefreshVisibility;
  flyToView?: FlyToView;
  link?: Link1;
  url?: Url;
  [k: string]: unknown;
}
