/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetWcsCrs10 =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "supportedCrs";
        namespaceURI?: "http://www.opengis.net/wcs/crs/1.0";
        [k: string]: unknown;
      };
      /**
       * http://www.w3.org/TR/xmlschema-2/#anyURI
       */
      value?: string | null;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "outputCrs";
        namespaceURI?: "http://www.opengis.net/wcs/crs/1.0";
        [k: string]: unknown;
      };
      /**
       * http://www.w3.org/TR/xmlschema-2/#anyURI
       */
      value?: string | null;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "subsettingCrs";
        namespaceURI?: "http://www.opengis.net/wcs/crs/1.0";
        [k: string]: unknown;
      };
      /**
       * http://www.w3.org/TR/xmlschema-2/#anyURI
       */
      value?: string | null;
      [k: string]: unknown;
    };
