/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetWcsInterpolation10 =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Interpolation";
        namespaceURI?: "http://www.opengis.net/wcs/interpolation/1.0";
        [k: string]: unknown;
      };
      value?: InterpolationType;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "InterpolationMetadata";
        namespaceURI?: "http://www.opengis.net/wcs/interpolation/1.0";
        [k: string]: unknown;
      };
      value?: InterpolationMetadataType;
      [k: string]: unknown;
    };
export type GlobalInterpolation = string | null;
export type InterpolationPerAxis = InterpolationPerAxisType[];
export type Axis = string | null;
export type InterpolationMethod = string | null;
export type InterpolationSupported = (string | null)[];

export interface InterpolationType {
  globalInterpolation: GlobalInterpolation;
  interpolationPerAxis?: InterpolationPerAxis;
  [k: string]: unknown;
}
export interface InterpolationPerAxisType {
  axis: Axis;
  interpolationMethod: InterpolationMethod;
  [k: string]: unknown;
}
export interface InterpolationMetadataType {
  interpolationSupported?: InterpolationSupported;
  [k: string]: unknown;
}
