/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetWcsRangeSubsetting10 = {
  name?: ({
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null) & {
    localPart?: "RangeSubset";
    namespaceURI?: "http://www.opengis.net/wcs/range-subsetting/1.0";
    [k: string]: unknown;
  };
  value?: RangeSubsetType;
  [k: string]: unknown;
};
export type RangeItem = [RangeItemType, ...RangeItemType[]];
export type RangeComponent = string | null;
export type RangeInterval = RangeIntervalType;
export type StartComponent = string | null;
export type EndComponent = string | null;

export interface RangeSubsetType {
  rangeItem: RangeItem;
  [k: string]: unknown;
}
export interface RangeItemType {
  rangeComponent: RangeComponent;
  rangeInterval: RangeInterval;
  [k: string]: unknown;
}
export interface RangeIntervalType {
  startComponent: StartComponent;
  endComponent: EndComponent;
  [k: string]: unknown;
}
