/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetWcsScaling10 = {
  name?: ({
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null) & {
    localPart?: "Scaling";
    namespaceURI?: "http://www.opengis.net/wcs/scaling/1.0";
    [k: string]: unknown;
  };
  value?: ScalingType;
  [k: string]: unknown;
};
export type ScaleByFactor = ScaleByFactorType;
export type ScaleFactor = number | null;
export type ScaleAxesByFactor = ScaleAxesByFactorType;
export type ScaleAxis = [ScaleAxisType, ...ScaleAxisType[]];
export type Axis = string | null;
export type ScaleFactor1 = number | null;
export type ScaleToSize = ScaleToSizeType;
export type TargetAxisSize = [TargetAxisSizeType, ...TargetAxisSizeType[]];
export type Axis1 = string | null;
export type TargetSize = number | null;
export type ScaleToExtent = ScaleToExtentType;
export type TargetAxisExtent = [TargetAxisExtentType, ...TargetAxisExtentType[]];
export type Axis2 = string | null;
export type Low = number | null;
export type High = number | null;

export interface ScalingType {
  scaleByFactor: ScaleByFactor;
  scaleAxesByFactor: ScaleAxesByFactor;
  scaleToSize: ScaleToSize;
  scaleToExtent: ScaleToExtent;
  [k: string]: unknown;
}
export interface ScaleByFactorType {
  scaleFactor: ScaleFactor;
  [k: string]: unknown;
}
export interface ScaleAxesByFactorType {
  scaleAxis: ScaleAxis;
  [k: string]: unknown;
}
export interface ScaleAxisType {
  axis: Axis;
  scaleFactor: ScaleFactor1;
  [k: string]: unknown;
}
export interface ScaleToSizeType {
  targetAxisSize: TargetAxisSize;
  [k: string]: unknown;
}
export interface TargetAxisSizeType {
  axis: Axis1;
  targetSize: TargetSize;
  [k: string]: unknown;
}
export interface ScaleToExtentType {
  targetAxisExtent: TargetAxisExtent;
  [k: string]: unknown;
}
export interface TargetAxisExtentType {
  axis: Axis2;
  low: Low;
  high: High;
  [k: string]: unknown;
}
