/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GML.3";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GML3;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "WMS_XML";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: WMSXML;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "FeatureInfo";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: FeatureInfo;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GML.1";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GML1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Capability";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Capability;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Request";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Request;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Style";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Style;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "WebCGM";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: WebCGM;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GIF";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GIF;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Capabilities";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Capabilities;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "MIME";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MIME;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "BLANK";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: BLANK;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "TIFF";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: TIFF;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GML.2";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GML2;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "JPEG";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: JPEG;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PPM";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PPM;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PNG";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PNG;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Service";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Service;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Layer";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Layer;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "BoundingBox";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: BoundingBox;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "WMT_MS_Capabilities";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: WMTMSCapabilities;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "HTTP";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: HTTP;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "WBMP";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: WBMP;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Post";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Post;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GeoTIFF";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GeoTIFF;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ScaleHint";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ScaleHint;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Exception";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Exception;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Format";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Format;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "INIMAGE";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: INIMAGE;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LatLonBoundingBox";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LatLonBoundingBox;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Get";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Get;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Map";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Map;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "SVG";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: SVG;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "VendorSpecificCapabilities";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: VendorSpecificCapabilities;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "DCPType";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: DCPType;
      [k: string]: unknown;
    };
export type Format1 = Format;
export type GifOrJPEGOrPNGOrWebCGMOrSVGOrGML1OrGML2OrGML3OrWBMPOrWMSXMLOrMIMEOrINIMAGEOrTIFFOrGeoTIFFOrPPMOrBLANK = (
  | GIF
  | JPEG
  | PNG
  | WebCGM
  | SVG
  | GML1
  | GML2
  | GML3
  | WBMP
  | WMSXML
  | MIME
  | INIMAGE
  | TIFF
  | GeoTIFF
  | PPM
  | BLANK
)[];
export type DcpType = DCPType[];
export type Http = HTTP;
export type GetOrPost = (Get | Post)[];
export type OnlineResource = string | null;
export type OnlineResource1 = string | null;
export type Request1 = Request;
export type MapOrCapabilitiesOrFeatureInfo = (Map | Capabilities | FeatureInfo)[];
export type Format2 = Format;
export type DcpType1 = DCPType[];
export type Format3 = Format;
export type DcpType2 = DCPType[];
export type Exception1 = Exception;
export type Format4 = Format;
export type VendorSpecificCapabilities1 = VendorSpecificCapabilities;
export type Layer2 = Layer;
export type Queryable = string | null;
export type Name = string | null;
export type Title = string | null;
export type _Abstract = string | null;
export type Keywords = string | null;
export type Srs = string | null;
export type LatLonBoundingBox1 = LatLonBoundingBox;
export type Minx = string | null;
export type Miny = string | null;
export type Maxx = string | null;
export type Maxy = string | null;
export type BoundingBox1 = BoundingBox[];
export type Srs1 = string | null;
export type Minx1 = string | null;
export type Miny1 = string | null;
export type Maxx1 = string | null;
export type Maxy1 = string | null;
export type DataURL = string | null;
export type Style1 = Style[];
export type Name1 = string | null;
export type Title1 = string | null;
export type _Abstract1 = string | null;
export type StyleURL = string | null;
export type ScaleHint1 = ScaleHint;
export type Min = string | null;
export type Max = string | null;
export type Layer1 = Layer[];
export type Name2 = string | null;
export type Title2 = string | null;
export type _Abstract2 = string | null;
export type Keywords1 = string | null;
export type OnlineResource2 = string | null;
export type Fees = string | null;
export type AccessConstraints = string | null;
export type Version = string | null;
export type UpdateSequence = string | null;
export type Service1 = Service;
export type Capability1 = Capability;

export interface GML3 {
  [k: string]: unknown;
}
export interface WMSXML {
  [k: string]: unknown;
}
export interface FeatureInfo {
  format?: Format1;
  dcpType?: DcpType;
  [k: string]: unknown;
}
export interface Format {
  gifOrJPEGOrPNGOrWebCGMOrSVGOrGML1OrGML2OrGML3OrWBMPOrWMSXMLOrMIMEOrINIMAGEOrTIFFOrGeoTIFFOrPPMOrBLANK?: GifOrJPEGOrPNGOrWebCGMOrSVGOrGML1OrGML2OrGML3OrWBMPOrWMSXMLOrMIMEOrINIMAGEOrTIFFOrGeoTIFFOrPPMOrBLANK;
  [k: string]: unknown;
}
export interface GIF {
  [k: string]: unknown;
}
export interface JPEG {
  [k: string]: unknown;
}
export interface PNG {
  [k: string]: unknown;
}
export interface WebCGM {
  [k: string]: unknown;
}
export interface SVG {
  [k: string]: unknown;
}
export interface GML1 {
  [k: string]: unknown;
}
export interface GML2 {
  [k: string]: unknown;
}
export interface WBMP {
  [k: string]: unknown;
}
export interface MIME {
  [k: string]: unknown;
}
export interface INIMAGE {
  [k: string]: unknown;
}
export interface TIFF {
  [k: string]: unknown;
}
export interface GeoTIFF {
  [k: string]: unknown;
}
export interface PPM {
  [k: string]: unknown;
}
export interface BLANK {
  [k: string]: unknown;
}
export interface DCPType {
  http?: Http;
  [k: string]: unknown;
}
export interface HTTP {
  getOrPost?: GetOrPost;
  [k: string]: unknown;
}
export interface Get {
  onlineResource?: OnlineResource;
  [k: string]: unknown;
}
export interface Post {
  onlineResource?: OnlineResource1;
  [k: string]: unknown;
}
export interface Capability {
  request?: Request1;
  exception?: Exception1;
  vendorSpecificCapabilities?: VendorSpecificCapabilities1;
  layer?: Layer2;
  [k: string]: unknown;
}
export interface Request {
  mapOrCapabilitiesOrFeatureInfo?: MapOrCapabilitiesOrFeatureInfo;
  [k: string]: unknown;
}
export interface Map {
  format?: Format2;
  dcpType?: DcpType1;
  [k: string]: unknown;
}
export interface Capabilities {
  format?: Format3;
  dcpType?: DcpType2;
  [k: string]: unknown;
}
export interface Exception {
  format?: Format4;
  [k: string]: unknown;
}
export interface VendorSpecificCapabilities {
  [k: string]: unknown;
}
export interface Layer {
  queryable?: Queryable;
  name?: Name;
  title?: Title;
  _abstract?: _Abstract;
  keywords?: Keywords;
  srs?: Srs;
  latLonBoundingBox?: LatLonBoundingBox1;
  boundingBox?: BoundingBox1;
  dataURL?: DataURL;
  style?: Style1;
  scaleHint?: ScaleHint1;
  layer?: Layer1;
  [k: string]: unknown;
}
export interface LatLonBoundingBox {
  minx?: Minx;
  miny?: Miny;
  maxx?: Maxx;
  maxy?: Maxy;
  [k: string]: unknown;
}
export interface BoundingBox {
  srs?: Srs1;
  minx?: Minx1;
  miny?: Miny1;
  maxx?: Maxx1;
  maxy?: Maxy1;
  [k: string]: unknown;
}
export interface Style {
  name?: Name1;
  title?: Title1;
  _abstract?: _Abstract1;
  styleURL?: StyleURL;
  [k: string]: unknown;
}
export interface ScaleHint {
  min?: Min;
  max?: Max;
  [k: string]: unknown;
}
export interface Service {
  name?: Name2;
  title?: Title2;
  _abstract?: _Abstract2;
  keywords?: Keywords1;
  onlineResource?: OnlineResource2;
  fees?: Fees;
  accessConstraints?: AccessConstraints;
  [k: string]: unknown;
}
export interface WMTMSCapabilities {
  version?: Version;
  updateSequence?: UpdateSequence;
  service?: Service1;
  capability?: Capability1;
  [k: string]: unknown;
}
