/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpWwwOpengisNetOgc = {
  name?: ({
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null) & {
    localPart?: "ServiceExceptionReport";
    namespaceURI?: "http://www.opengis.net/ogc";
    [k: string]: unknown;
  };
  value?: ServiceExceptionReport;
  [k: string]: unknown;
};
export type ServiceException = ServiceExceptionType[];
export type Value = string | null;
export type Code = string | null;
export type Locator = string | null;
export type Version = string | null;

export interface ServiceExceptionReport {
  serviceException?: ServiceException;
  version?: Version;
  [k: string]: unknown;
}
export interface ServiceExceptionType {
  value?: Value;
  code?: Code;
  locator?: Locator;
  [k: string]: unknown;
}
