/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LogoURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LogoURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ContactInformation";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ContactInformation;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ContactPersonPrimary";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ContactPersonPrimary;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Format";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Format;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "KeywordList";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: KeywordList;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Style";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Style;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Capability";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Capability;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ServiceExceptionReport";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ServiceExceptionReport;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "BoundingBox";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: BoundingBox;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "FeatureListURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: FeatureListURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ServiceException";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ServiceException;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "VendorSpecificCapabilities";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: VendorSpecificCapabilities;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Service";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Service;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "WMS_DescribeLayerResponse";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: WMSDescribeLayerResponse;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GetCapabilities";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GetCapabilities;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ScaleHint";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ScaleHint;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ContactAddress";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: ContactAddress;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Query";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Query;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "SRS";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: SRS;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "DataURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: DataURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Extent";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Extent;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Request";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Request;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GetFeatureInfo";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GetFeatureInfo;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GetLegendGraphic";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GetLegendGraphic;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GetStyles";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GetStyles;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "AuthorityURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: AuthorityURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LatLonBoundingBox";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LatLonBoundingBox;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Exception";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Exception;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "HTTP";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: HTTP;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "MetadataURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: MetadataURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "WMT_MS_Capabilities";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: WMTMSCapabilities;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "StyleSheetURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: StyleSheetURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "GetMap";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: GetMap;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "DescribeLayer";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: DescribeLayer;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Dimension";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Dimension;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Get";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Get;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "OnlineResource";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: OnlineResource;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "DCPType";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: DCPType;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Post";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Post;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Attribution";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Attribution;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Identifier";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Identifier;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PutStyles";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: PutStyles;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "UserDefinedSymbolization";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: UserDefinedSymbolization;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LegendURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LegendURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "LayerDescription";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: LayerDescription;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "StyleURL";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: StyleURL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Layer";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Layer;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Keyword";
        namespaceURI?: "";
        [k: string]: unknown;
      };
      value?: Keyword;
      [k: string]: unknown;
    };
export type Width = string | null;
export type Height = string | null;
export type Format1 = Format;
export type Value = string | null;
export type OnlineResource1 = OnlineResource;
export type XmlnsXlink = string | null;
export type XlinkType = string | null;
export type XlinkHref = string | null;
export type ContactPersonPrimary1 = ContactPersonPrimary;
export type ContactPerson = string | null;
export type ContactOrganization = string | null;
export type ContactPosition = string | null;
export type ContactAddress1 = ContactAddress;
export type AddressType = string | null;
export type Address = string | null;
export type City = string | null;
export type StateOrProvince = string | null;
export type PostCode = string | null;
export type Country = string | null;
export type ContactVoiceTelephone = string | null;
export type ContactFacsimileTelephone = string | null;
export type ContactElectronicMailAddress = string | null;
export type Keyword1 = Keyword[];
export type Value1 = string | null;
export type Name = string | null;
export type Title = string | null;
export type _Abstract = string | null;
export type LegendURL1 = LegendURL[];
export type Width1 = string | null;
export type Height1 = string | null;
export type Format2 = Format;
export type OnlineResource2 = OnlineResource;
export type StyleSheetURL1 = StyleSheetURL;
export type Format3 = Format;
export type OnlineResource3 = OnlineResource;
export type StyleURL1 = StyleURL;
export type Format4 = Format;
export type OnlineResource4 = OnlineResource;
export type Request1 = Request;
export type GetCapabilities1 = GetCapabilities;
export type Format5 = Format[];
export type DcpType = DCPType[];
export type Http = HTTP;
export type GetOrPost = (Get | Post)[];
export type OnlineResource5 = OnlineResource;
export type OnlineResource6 = OnlineResource;
export type GetMap1 = GetMap;
export type Format6 = Format[];
export type DcpType1 = DCPType[];
export type GetFeatureInfo1 = GetFeatureInfo;
export type Format7 = Format[];
export type DcpType2 = DCPType[];
export type DescribeLayer1 = DescribeLayer;
export type Format8 = Format[];
export type DcpType3 = DCPType[];
export type GetLegendGraphic1 = GetLegendGraphic;
export type Format9 = Format[];
export type DcpType4 = DCPType[];
export type GetStyles1 = GetStyles;
export type Format10 = Format[];
export type DcpType5 = DCPType[];
export type PutStyles1 = PutStyles;
export type Format11 = Format[];
export type DcpType6 = DCPType[];
export type Exception1 = Exception;
export type Format12 = Format[];
export type VendorSpecificCapabilities1 = VendorSpecificCapabilities;
export type UserDefinedSymbolization1 = UserDefinedSymbolization;
export type SupportSLD = string | null;
export type UserLayer = string | null;
export type UserStyle = string | null;
export type RemoteWFS = string | null;
export type Layer2 = Layer;
export type Queryable = string | null;
export type Cascaded = string | null;
export type Opaque = string | null;
export type NoSubsets = string | null;
export type FixedWidth = string | null;
export type FixedHeight = string | null;
export type Name1 = string | null;
export type Title1 = string | null;
export type _Abstract1 = string | null;
export type KeywordList1 = KeywordList;
export type Srs = SRS[];
export type Value2 = string | null;
export type LatLonBoundingBox1 = LatLonBoundingBox;
export type Minx = string | null;
export type Miny = string | null;
export type Maxx = string | null;
export type Maxy = string | null;
export type BoundingBox1 = BoundingBox[];
export type Srs1 = string | null;
export type Minx1 = string | null;
export type Miny1 = string | null;
export type Maxx1 = string | null;
export type Maxy1 = string | null;
export type Resx = string | null;
export type Resy = string | null;
export type Dimension1 = Dimension[];
export type Name2 = string | null;
export type Units = string | null;
export type UnitSymbol = string | null;
export type Extent1 = Extent[];
export type Name3 = string | null;
export type _Default = string | null;
export type NearestValue = string | null;
export type MultipleValues = string | null;
export type Current = string | null;
export type Value3 = string | null;
export type Attribution1 = Attribution;
export type Title2 = string | null;
export type OnlineResource7 = OnlineResource;
export type LogoURL1 = LogoURL;
export type AuthorityURL1 = AuthorityURL[];
export type Name4 = string | null;
export type OnlineResource8 = OnlineResource;
export type Identifier1 = Identifier[];
export type Authority = string | null;
export type Value4 = string | null;
export type MetadataURL1 = MetadataURL[];
export type Type = string | null;
export type Format13 = Format;
export type OnlineResource9 = OnlineResource;
export type DataURL1 = DataURL[];
export type Format14 = Format;
export type OnlineResource10 = OnlineResource;
export type FeatureListURL1 = FeatureListURL[];
export type Format15 = Format;
export type OnlineResource11 = OnlineResource;
export type Style1 = Style[];
export type ScaleHint1 = ScaleHint;
export type Min = string | null;
export type Max = string | null;
export type Layer1 = Layer[];
export type Version = string | null;
export type ServiceException1 = ServiceException[];
export type Code = string | null;
export type Value5 = string | null;
export type Name5 = string | null;
export type Title3 = string | null;
export type _Abstract2 = string | null;
export type KeywordList2 = KeywordList;
export type OnlineResource12 = OnlineResource;
export type ContactInformation1 = ContactInformation;
export type Fees = string | null;
export type AccessConstraints = string | null;
export type Version1 = string | null;
export type LayerDescription1 = LayerDescription[];
export type Name6 = string | null;
export type Wfs = string | null;
export type OwsType = string | null;
export type OwsURL = string | null;
export type Query1 = Query[];
export type TypeName = string | null;
export type Version2 = string | null;
export type UpdateSequence = string | null;
export type Service1 = Service;
export type Capability1 = Capability;

export interface LogoURL {
  width?: Width;
  height?: Height;
  format?: Format1;
  onlineResource?: OnlineResource1;
  [k: string]: unknown;
}
export interface Format {
  value?: Value;
  [k: string]: unknown;
}
export interface OnlineResource {
  xmlnsXlink?: XmlnsXlink;
  xlinkType?: XlinkType;
  xlinkHref?: XlinkHref;
  [k: string]: unknown;
}
export interface ContactInformation {
  contactPersonPrimary?: ContactPersonPrimary1;
  contactPosition?: ContactPosition;
  contactAddress?: ContactAddress1;
  contactVoiceTelephone?: ContactVoiceTelephone;
  contactFacsimileTelephone?: ContactFacsimileTelephone;
  contactElectronicMailAddress?: ContactElectronicMailAddress;
  [k: string]: unknown;
}
export interface ContactPersonPrimary {
  contactPerson?: ContactPerson;
  contactOrganization?: ContactOrganization;
  [k: string]: unknown;
}
export interface ContactAddress {
  addressType?: AddressType;
  address?: Address;
  city?: City;
  stateOrProvince?: StateOrProvince;
  postCode?: PostCode;
  country?: Country;
  [k: string]: unknown;
}
export interface KeywordList {
  keyword?: Keyword1;
  [k: string]: unknown;
}
export interface Keyword {
  value?: Value1;
  [k: string]: unknown;
}
export interface Style {
  name?: Name;
  title?: Title;
  _abstract?: _Abstract;
  legendURL?: LegendURL1;
  styleSheetURL?: StyleSheetURL1;
  styleURL?: StyleURL1;
  [k: string]: unknown;
}
export interface LegendURL {
  width?: Width1;
  height?: Height1;
  format?: Format2;
  onlineResource?: OnlineResource2;
  [k: string]: unknown;
}
export interface StyleSheetURL {
  format?: Format3;
  onlineResource?: OnlineResource3;
  [k: string]: unknown;
}
export interface StyleURL {
  format?: Format4;
  onlineResource?: OnlineResource4;
  [k: string]: unknown;
}
export interface Capability {
  request?: Request1;
  exception?: Exception1;
  vendorSpecificCapabilities?: VendorSpecificCapabilities1;
  userDefinedSymbolization?: UserDefinedSymbolization1;
  layer?: Layer2;
  [k: string]: unknown;
}
export interface Request {
  getCapabilities?: GetCapabilities1;
  getMap?: GetMap1;
  getFeatureInfo?: GetFeatureInfo1;
  describeLayer?: DescribeLayer1;
  getLegendGraphic?: GetLegendGraphic1;
  getStyles?: GetStyles1;
  putStyles?: PutStyles1;
  [k: string]: unknown;
}
export interface GetCapabilities {
  format?: Format5;
  dcpType?: DcpType;
  [k: string]: unknown;
}
export interface DCPType {
  http?: Http;
  [k: string]: unknown;
}
export interface HTTP {
  getOrPost?: GetOrPost;
  [k: string]: unknown;
}
export interface Get {
  onlineResource?: OnlineResource5;
  [k: string]: unknown;
}
export interface Post {
  onlineResource?: OnlineResource6;
  [k: string]: unknown;
}
export interface GetMap {
  format?: Format6;
  dcpType?: DcpType1;
  [k: string]: unknown;
}
export interface GetFeatureInfo {
  format?: Format7;
  dcpType?: DcpType2;
  [k: string]: unknown;
}
export interface DescribeLayer {
  format?: Format8;
  dcpType?: DcpType3;
  [k: string]: unknown;
}
export interface GetLegendGraphic {
  format?: Format9;
  dcpType?: DcpType4;
  [k: string]: unknown;
}
export interface GetStyles {
  format?: Format10;
  dcpType?: DcpType5;
  [k: string]: unknown;
}
export interface PutStyles {
  format?: Format11;
  dcpType?: DcpType6;
  [k: string]: unknown;
}
export interface Exception {
  format?: Format12;
  [k: string]: unknown;
}
export interface VendorSpecificCapabilities {
  [k: string]: unknown;
}
export interface UserDefinedSymbolization {
  supportSLD?: SupportSLD;
  userLayer?: UserLayer;
  userStyle?: UserStyle;
  remoteWFS?: RemoteWFS;
  [k: string]: unknown;
}
export interface Layer {
  queryable?: Queryable;
  cascaded?: Cascaded;
  opaque?: Opaque;
  noSubsets?: NoSubsets;
  fixedWidth?: FixedWidth;
  fixedHeight?: FixedHeight;
  name?: Name1;
  title?: Title1;
  _abstract?: _Abstract1;
  keywordList?: KeywordList1;
  srs?: Srs;
  latLonBoundingBox?: LatLonBoundingBox1;
  boundingBox?: BoundingBox1;
  dimension?: Dimension1;
  extent?: Extent1;
  attribution?: Attribution1;
  authorityURL?: AuthorityURL1;
  identifier?: Identifier1;
  metadataURL?: MetadataURL1;
  dataURL?: DataURL1;
  featureListURL?: FeatureListURL1;
  style?: Style1;
  scaleHint?: ScaleHint1;
  layer?: Layer1;
  [k: string]: unknown;
}
export interface SRS {
  value?: Value2;
  [k: string]: unknown;
}
export interface LatLonBoundingBox {
  minx?: Minx;
  miny?: Miny;
  maxx?: Maxx;
  maxy?: Maxy;
  [k: string]: unknown;
}
export interface BoundingBox {
  srs?: Srs1;
  minx?: Minx1;
  miny?: Miny1;
  maxx?: Maxx1;
  maxy?: Maxy1;
  resx?: Resx;
  resy?: Resy;
  [k: string]: unknown;
}
export interface Dimension {
  name?: Name2;
  units?: Units;
  unitSymbol?: UnitSymbol;
  [k: string]: unknown;
}
export interface Extent {
  name?: Name3;
  _default?: _Default;
  nearestValue?: NearestValue;
  multipleValues?: MultipleValues;
  current?: Current;
  value?: Value3;
  [k: string]: unknown;
}
export interface Attribution {
  title?: Title2;
  onlineResource?: OnlineResource7;
  logoURL?: LogoURL1;
  [k: string]: unknown;
}
export interface AuthorityURL {
  name?: Name4;
  onlineResource?: OnlineResource8;
  [k: string]: unknown;
}
export interface Identifier {
  authority?: Authority;
  value?: Value4;
  [k: string]: unknown;
}
export interface MetadataURL {
  type?: Type;
  format?: Format13;
  onlineResource?: OnlineResource9;
  [k: string]: unknown;
}
export interface DataURL {
  format?: Format14;
  onlineResource?: OnlineResource10;
  [k: string]: unknown;
}
export interface FeatureListURL {
  format?: Format15;
  onlineResource?: OnlineResource11;
  [k: string]: unknown;
}
export interface ScaleHint {
  min?: Min;
  max?: Max;
  [k: string]: unknown;
}
export interface ServiceExceptionReport {
  version?: Version;
  serviceException?: ServiceException1;
  [k: string]: unknown;
}
export interface ServiceException {
  code?: Code;
  value?: Value5;
  [k: string]: unknown;
}
export interface Service {
  name?: Name5;
  title?: Title3;
  _abstract?: _Abstract2;
  keywordList?: KeywordList2;
  onlineResource?: OnlineResource12;
  contactInformation?: ContactInformation1;
  fees?: Fees;
  accessConstraints?: AccessConstraints;
  [k: string]: unknown;
}
export interface WMSDescribeLayerResponse {
  version?: Version1;
  layerDescription?: LayerDescription1;
  [k: string]: unknown;
}
export interface LayerDescription {
  name?: Name6;
  wfs?: Wfs;
  owsType?: OwsType;
  owsURL?: OwsURL;
  query?: Query1;
  [k: string]: unknown;
}
export interface Query {
  typeName?: TypeName;
  [k: string]: unknown;
}
export interface WMTMSCapabilities {
  version?: Version2;
  updateSequence?: UpdateSequence;
  service?: Service1;
  capability?: Capability1;
  [k: string]: unknown;
}
