/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpDocsOasisOpenOrgWsnT1 =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "TopicNamespace";
        namespaceURI?: "http://docs.oasis-open.org/wsn/t-1";
        [k: string]: unknown;
      };
      value?: TopicNamespaceType1;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "TopicSet";
        namespaceURI?: "http://docs.oasis-open.org/wsn/t-1";
        [k: string]: unknown;
      };
      value?: TopicSetType1;
      [k: string]: unknown;
    };
export type TopicNamespaceType1 = ExtensibleDocumented & TopicNamespaceType;
export type OtherAttributes = {
  [k: string]: string;
};
export type Documentation1 = Documentation;
export type Content = (
  | (string | null)
  | unknown
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: unknown;
      [k: string]: unknown;
    }
)[];
export type OtherAttributes1 = {
  [k: string]: string;
};
export type Topic1 = TopicNamespaceTypeTopic1[];
export type TopicNamespaceTypeTopic1 = TopicType1 & TopicNamespaceTypeTopic;
export type TopicType1 = ExtensibleDocumented & TopicType;
export type OtherAttributes2 = {
  [k: string]: string;
};
export type MessagePattern = QueryExpressionType;
export type Content1 = (
  | (string | null)
  | unknown
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: unknown;
      [k: string]: unknown;
    }
)[];
export type Dialect = string | null;
export type Topic = TopicType1[];
export type Any = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Name = string | null;
export type MessageTypes = ({
  namespaceURI?: (string | null) | "";
  /**
   * http://www.w3.org/TR/xmlschema-2/#NCName
   */
  localPart: string | null;
  prefix?: (string | null) | "";
  [k: string]: unknown;
} | null)[];
export type _Final = boolean | null;
export type OtherAttributes3 = {
  [k: string]: string;
};
export type Parent = string | null;
export type Any1 = (
  | unknown
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: unknown;
      [k: string]: unknown;
    }
)[];
export type Name1 = string | null;
export type TargetNamespace = string | null;
export type _Final1 = boolean | null;
export type TopicSetType1 = ExtensibleDocumented & TopicSetType;
export type OtherAttributes4 = {
  [k: string]: string;
};
export type Any2 = (
  | unknown
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: unknown;
      [k: string]: unknown;
    }
)[];

export interface ExtensibleDocumented {
  otherAttributes?: OtherAttributes;
  documentation?: Documentation1;
  [k: string]: unknown;
}
export interface Documentation {
  content?: Content;
  [k: string]: unknown;
}
export interface TopicNamespaceType {
  otherAttributes?: OtherAttributes1;
  topic?: Topic1;
  any?: Any1;
  name?: Name1;
  targetNamespace?: TargetNamespace;
  _final?: _Final1;
  [k: string]: unknown;
}
export interface TopicType {
  otherAttributes?: OtherAttributes2;
  messagePattern?: MessagePattern;
  topic?: Topic;
  any?: Any;
  name?: Name;
  messageTypes?: MessageTypes;
  _final?: _Final;
  [k: string]: unknown;
}
export interface QueryExpressionType {
  content?: Content1;
  dialect: Dialect;
  [k: string]: unknown;
}
export interface TopicNamespaceTypeTopic {
  otherAttributes?: OtherAttributes3;
  parent?: Parent;
  [k: string]: unknown;
}
export interface TopicSetType {
  otherAttributes?: OtherAttributes4;
  any?: Any2;
  [k: string]: unknown;
}
