/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UrnOasisNamesTcCiqXsdschemaXAL20 =
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "AddressDetails";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: AddressDetails;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Thoroughfare";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: Thoroughfare;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ThoroughfareNumberSuffix";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: ThoroughfareNumberSuffix;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Locality";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: Locality;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ThoroughfareNumberPrefix";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: ThoroughfareNumberPrefix;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PostOffice";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: PostOffice;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PostBox";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: PostBox;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Premise";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: Premise;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "ThoroughfareNumber";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: ThoroughfareNumber;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PremiseNumberPrefix";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: PremiseNumberPrefix;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "AddressLine";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: AddressLine;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "CountryName";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: CountryName;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PostalCode";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: PostalCode;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "Department";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: Department;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PremiseNumber";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: PremiseNumber;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "AdministrativeArea";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: AdministrativeArea;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "xAL";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: XAL;
      [k: string]: unknown;
    }
  | {
      name?: ({
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null) & {
        localPart?: "PremiseNumberSuffix";
        namespaceURI?: "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0";
        [k: string]: unknown;
      };
      value?: PremiseNumberSuffix;
      [k: string]: unknown;
    };
export type OtherAttributes = {
  [k: string]: string;
};
export type PostalServiceElements = AddressDetailsPostalServiceElements;
export type OtherAttributes1 = {
  [k: string]: string;
};
export type AddressIdentifier = AddressDetailsPostalServiceElementsAddressIdentifier[];
export type OtherAttributes2 = {
  [k: string]: string;
};
export type Content = string | null;
export type IdentifierType = string | number | boolean | null;
export type Type = string | number | boolean | null;
export type Code = string | number | boolean | null;
export type EndorsementLineCode = AddressDetailsPostalServiceElementsEndorsementLineCode;
export type OtherAttributes3 = {
  [k: string]: string;
};
export type Content1 = string | null;
export type Type1 = string | number | boolean | null;
export type Code1 = string | number | boolean | null;
export type KeyLineCode = AddressDetailsPostalServiceElementsKeyLineCode;
export type OtherAttributes4 = {
  [k: string]: string;
};
export type Content2 = string | null;
export type Type2 = string | number | boolean | null;
export type Code2 = string | number | boolean | null;
export type Barcode = AddressDetailsPostalServiceElementsBarcode;
export type OtherAttributes5 = {
  [k: string]: string;
};
export type Content3 = string | null;
export type Type3 = string | number | boolean | null;
export type Code3 = string | number | boolean | null;
export type SortingCode = AddressDetailsPostalServiceElementsSortingCode;
export type Type4 = string | number | boolean | null;
export type Code4 = string | number | boolean | null;
export type AddressLatitude = AddressDetailsPostalServiceElementsAddressLatitude;
export type OtherAttributes6 = {
  [k: string]: string;
};
export type Content4 = string | null;
export type Type5 = string | number | boolean | null;
export type Code5 = string | number | boolean | null;
export type AddressLatitudeDirection = AddressDetailsPostalServiceElementsAddressLatitudeDirection;
export type OtherAttributes7 = {
  [k: string]: string;
};
export type Content5 = string | null;
export type Type6 = string | number | boolean | null;
export type Code6 = string | number | boolean | null;
export type AddressLongitude = AddressDetailsPostalServiceElementsAddressLongitude;
export type OtherAttributes8 = {
  [k: string]: string;
};
export type Content6 = string | null;
export type Type7 = string | number | boolean | null;
export type Code7 = string | number | boolean | null;
export type AddressLongitudeDirection = AddressDetailsPostalServiceElementsAddressLongitudeDirection;
export type OtherAttributes9 = {
  [k: string]: string;
};
export type Content7 = string | null;
export type Type8 = string | number | boolean | null;
export type Code8 = string | number | boolean | null;
export type SupplementaryPostalServiceData = AddressDetailsPostalServiceElementsSupplementaryPostalServiceData[];
export type OtherAttributes10 = {
  [k: string]: string;
};
export type Content8 = string | null;
export type Type9 = string | number | boolean | null;
export type Code9 = string | number | boolean | null;
export type Any = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type10 = string | number | boolean | null;
export type Address = AddressDetailsAddress;
export type OtherAttributes11 = {
  [k: string]: string;
};
export type Content9 = string | null;
export type Type11 = string | number | boolean | null;
export type Code10 = string | number | boolean | null;
export type AddressLines = AddressLinesType;
export type OtherAttributes12 = {
  [k: string]: string;
};
export type AddressLine1 = [AddressLine, ...AddressLine[]];
export type OtherAttributes13 = {
  [k: string]: string;
};
export type Content10 = string | null;
export type Type12 = string | number | boolean | null;
export type Code11 = string | number | boolean | null;
export type Any1 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Country = AddressDetailsCountry;
export type OtherAttributes14 = {
  [k: string]: string;
};
export type AddressLine2 = AddressLine[];
export type CountryNameCode = AddressDetailsCountryCountryNameCode[];
export type OtherAttributes15 = {
  [k: string]: string;
};
export type Content11 = string | null;
export type Scheme = string | number | boolean | null;
export type Code12 = string | number | boolean | null;
export type CountryName1 = CountryName[];
export type OtherAttributes16 = {
  [k: string]: string;
};
export type Content12 = string | null;
export type Type13 = string | number | boolean | null;
export type Code13 = string | number | boolean | null;
export type AdministrativeArea1 = AdministrativeArea;
export type OtherAttributes17 = {
  [k: string]: string;
};
export type AddressLine3 = AddressLine[];
export type AdministrativeAreaName = AdministrativeAreaAdministrativeAreaName[];
export type OtherAttributes18 = {
  [k: string]: string;
};
export type Content13 = string | null;
export type Type14 = string | number | boolean | null;
export type Code14 = string | number | boolean | null;
export type SubAdministrativeArea = AdministrativeAreaSubAdministrativeArea;
export type OtherAttributes19 = {
  [k: string]: string;
};
export type AddressLine4 = AddressLine[];
export type SubAdministrativeAreaName = AdministrativeAreaSubAdministrativeAreaSubAdministrativeAreaName[];
export type OtherAttributes20 = {
  [k: string]: string;
};
export type Content14 = string | null;
export type Type15 = string | number | boolean | null;
export type Code15 = string | number | boolean | null;
export type Locality1 = Locality;
export type OtherAttributes21 = {
  [k: string]: string;
};
export type AddressLine5 = AddressLine[];
export type LocalityName = LocalityLocalityName[];
export type OtherAttributes22 = {
  [k: string]: string;
};
export type Content15 = string | null;
export type Type16 = string | number | boolean | null;
export type Code16 = string | number | boolean | null;
export type PostBox1 = PostBox;
export type OtherAttributes23 = {
  [k: string]: string;
};
export type AddressLine6 = AddressLine[];
export type PostBoxNumber = PostBoxPostBoxNumber;
export type OtherAttributes24 = {
  [k: string]: string;
};
export type Content16 = string | null;
export type Code17 = string | number | boolean | null;
export type PostBoxNumberPrefix = PostBoxPostBoxNumberPrefix;
export type OtherAttributes25 = {
  [k: string]: string;
};
export type Content17 = string | null;
export type NumberPrefixSeparator = string | number | boolean | null;
export type Code18 = string | number | boolean | null;
export type PostBoxNumberSuffix = PostBoxPostBoxNumberSuffix;
export type OtherAttributes26 = {
  [k: string]: string;
};
export type Content18 = string | null;
export type NumberSuffixSeparator = string | number | boolean | null;
export type Code19 = string | number | boolean | null;
export type PostBoxNumberExtension = PostBoxPostBoxNumberExtension;
export type OtherAttributes27 = {
  [k: string]: string;
};
export type Content19 = string | null;
export type NumberExtensionSeparator = string | number | boolean | null;
export type Firm = FirmType;
export type OtherAttributes28 = {
  [k: string]: string;
};
export type AddressLine7 = AddressLine[];
export type FirmName = FirmTypeFirmName[];
export type OtherAttributes29 = {
  [k: string]: string;
};
export type Content20 = string | null;
export type Type17 = string | number | boolean | null;
export type Code20 = string | number | boolean | null;
export type Department1 = Department[];
export type OtherAttributes30 = {
  [k: string]: string;
};
export type AddressLine8 = AddressLine[];
export type DepartmentName = DepartmentDepartmentName[];
export type OtherAttributes31 = {
  [k: string]: string;
};
export type Content21 = string | null;
export type Type18 = string | number | boolean | null;
export type Code21 = string | number | boolean | null;
export type MailStop = MailStopType;
export type OtherAttributes32 = {
  [k: string]: string;
};
export type AddressLine9 = AddressLine[];
export type MailStopName = MailStopTypeMailStopName;
export type OtherAttributes33 = {
  [k: string]: string;
};
export type Content22 = string | null;
export type Type19 = string | number | boolean | null;
export type Code22 = string | number | boolean | null;
export type MailStopNumber = MailStopTypeMailStopNumber;
export type OtherAttributes34 = {
  [k: string]: string;
};
export type Content23 = string | null;
export type NameNumberSeparator = string | number | boolean | null;
export type Code23 = string | number | boolean | null;
export type Any2 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type20 = string | number | boolean | null;
export type PostalCode1 = PostalCode;
export type OtherAttributes35 = {
  [k: string]: string;
};
export type AddressLine10 = AddressLine[];
export type PostalCodeNumber = PostalCodePostalCodeNumber[];
export type OtherAttributes36 = {
  [k: string]: string;
};
export type Content24 = string | null;
export type Type21 = string | number | boolean | null;
export type Code24 = string | number | boolean | null;
export type PostalCodeNumberExtension = PostalCodePostalCodeNumberExtension[];
export type OtherAttributes37 = {
  [k: string]: string;
};
export type Content25 = string | null;
export type Type22 = string | number | boolean | null;
export type NumberExtensionSeparator1 = string | number | boolean | null;
export type Code25 = string | number | boolean | null;
export type PostTown = PostalCodePostTown;
export type OtherAttributes38 = {
  [k: string]: string;
};
export type AddressLine11 = AddressLine[];
export type PostTownName = PostalCodePostTownPostTownName[];
export type OtherAttributes39 = {
  [k: string]: string;
};
export type Content26 = string | null;
export type Type23 = string | number | boolean | null;
export type Code26 = string | number | boolean | null;
export type PostTownSuffix = PostalCodePostTownPostTownSuffix;
export type OtherAttributes40 = {
  [k: string]: string;
};
export type Content27 = string | null;
export type Code27 = string | number | boolean | null;
export type Type24 = string | number | boolean | null;
export type Any3 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type25 = string | number | boolean | null;
export type Any4 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type26 = string | number | boolean | null;
export type MailStop1 = MailStopType;
export type PostalCode2 = PostalCode;
export type Any5 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type27 = string | number | boolean | null;
export type PostalCode3 = PostalCode;
export type Any6 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type28 = string | number | boolean | null;
export type Indicator = string | number | boolean | null;
export type LargeMailUser1 = LargeMailUserType;
export type OtherAttributes41 = {
  [k: string]: string;
};
export type AddressLine12 = AddressLine[];
export type LargeMailUserName = LargeMailUserTypeLargeMailUserName[];
export type OtherAttributes42 = {
  [k: string]: string;
};
export type Content28 = string | null;
export type Type29 = string | null;
export type Code28 = string | null;
export type LargeMailUserIdentifier = LargeMailUserTypeLargeMailUserIdentifier;
export type OtherAttributes43 = {
  [k: string]: string;
};
export type Content29 = string | null;
export type Type30 = string | null;
export type Indicator1 = string | number | boolean | null;
export type Code29 = string | number | boolean | null;
export type BuildingName = BuildingNameType[];
export type OtherAttributes44 = {
  [k: string]: string;
};
export type Content30 = string | null;
export type Type31 = string | number | boolean | null;
export type TypeOccurrence = string | null;
export type Code30 = string | number | boolean | null;
export type Department2 = Department;
export type PostBox2 = PostBox;
export type Thoroughfare2 = Thoroughfare;
export type OtherAttributes45 = {
  [k: string]: string;
};
export type AddressLine13 = AddressLine[];
export type ThoroughfareNumberOrThoroughfareNumberRange = (ThoroughfareNumber | ThoroughfareThoroughfareNumberRange)[];
export type OtherAttributes46 = {
  [k: string]: string;
};
export type Content31 = string | null;
export type NumberType = string | null;
export type Type32 = string | number | boolean | null;
export type Indicator2 = string | number | boolean | null;
export type IndicatorOccurrence = string | null;
export type NumberOccurrence = string | null;
export type Code31 = string | number | boolean | null;
export type OtherAttributes47 = {
  [k: string]: string;
};
export type AddressLine14 = AddressLine[];
export type ThoroughfareNumberFrom = ThoroughfareThoroughfareNumberRangeThoroughfareNumberFrom;
export type OtherAttributes48 = {
  [k: string]: string;
};
export type Content34 = (
  | (string | null)
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ThoroughfareNumberSuffix;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ThoroughfareNumber;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: AddressLine;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ThoroughfareNumberPrefix;
      [k: string]: unknown;
    }
)[];
export type OtherAttributes49 = {
  [k: string]: string;
};
export type Content32 = string | null;
export type NumberSuffixSeparator1 = string | number | boolean | null;
export type Type33 = string | number | boolean | null;
export type Code32 = string | number | boolean | null;
export type OtherAttributes50 = {
  [k: string]: string;
};
export type Content33 = string | null;
export type NumberPrefixSeparator1 = string | number | boolean | null;
export type Type34 = string | number | boolean | null;
export type Code33 = string | number | boolean | null;
export type Code34 = string | number | boolean | null;
export type ThoroughfareNumberTo = ThoroughfareThoroughfareNumberRangeThoroughfareNumberTo;
export type OtherAttributes51 = {
  [k: string]: string;
};
export type Content35 = (
  | (string | null)
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ThoroughfareNumberSuffix;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ThoroughfareNumber;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: AddressLine;
      [k: string]: unknown;
    }
  | {
      /**
       * http://www.w3.org/TR/xmlschema-2/#QName
       */
      name?: {
        namespaceURI?: (string | null) | "";
        /**
         * http://www.w3.org/TR/xmlschema-2/#NCName
         */
        localPart: string | null;
        prefix?: (string | null) | "";
        [k: string]: unknown;
      } | null;
      value?: ThoroughfareNumberPrefix;
      [k: string]: unknown;
    }
)[];
export type Code35 = string | number | boolean | null;
export type RangeType = string | null;
export type Indicator3 = string | number | boolean | null;
export type Separator = string | number | boolean | null;
export type IndicatorOccurrence1 = string | null;
export type NumberRangeOccurrence = string | null;
export type Type35 = string | number | boolean | null;
export type Code36 = string | number | boolean | null;
export type ThoroughfareNumberPrefix1 = ThoroughfareNumberPrefix[];
export type ThoroughfareNumberSuffix1 = ThoroughfareNumberSuffix[];
export type ThoroughfarePreDirection = ThoroughfarePreDirectionType;
export type OtherAttributes52 = {
  [k: string]: string;
};
export type Content36 = string | null;
export type Type36 = string | number | boolean | null;
export type Code37 = string | number | boolean | null;
export type ThoroughfareLeadingType = ThoroughfareLeadingTypeType;
export type OtherAttributes53 = {
  [k: string]: string;
};
export type Content37 = string | null;
export type Type37 = string | number | boolean | null;
export type Code38 = string | number | boolean | null;
export type ThoroughfareName = ThoroughfareNameType[];
export type OtherAttributes54 = {
  [k: string]: string;
};
export type Content38 = string | null;
export type Type38 = string | number | boolean | null;
export type Code39 = string | number | boolean | null;
export type ThoroughfareTrailingType = ThoroughfareTrailingTypeType;
export type OtherAttributes55 = {
  [k: string]: string;
};
export type Content39 = string | null;
export type Type39 = string | number | boolean | null;
export type Code40 = string | number | boolean | null;
export type ThoroughfarePostDirection = ThoroughfarePostDirectionType;
export type OtherAttributes56 = {
  [k: string]: string;
};
export type Content40 = string | null;
export type Type40 = string | number | boolean | null;
export type Code41 = string | number | boolean | null;
export type DependentThoroughfare = ThoroughfareDependentThoroughfare;
export type OtherAttributes57 = {
  [k: string]: string;
};
export type AddressLine15 = AddressLine[];
export type ThoroughfarePreDirection1 = ThoroughfarePreDirectionType;
export type ThoroughfareLeadingType1 = ThoroughfareLeadingTypeType;
export type ThoroughfareName1 = ThoroughfareNameType[];
export type ThoroughfareTrailingType1 = ThoroughfareTrailingTypeType;
export type ThoroughfarePostDirection1 = ThoroughfarePostDirectionType;
export type Any7 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type41 = string | number | boolean | null;
export type DependentLocality1 = DependentLocalityType;
export type OtherAttributes58 = {
  [k: string]: string;
};
export type AddressLine16 = AddressLine[];
export type DependentLocalityName = DependentLocalityTypeDependentLocalityName[];
export type OtherAttributes59 = {
  [k: string]: string;
};
export type Content41 = string | null;
export type Type42 = string | number | boolean | null;
export type Code42 = string | number | boolean | null;
export type DependentLocalityNumber = DependentLocalityTypeDependentLocalityNumber;
export type OtherAttributes60 = {
  [k: string]: string;
};
export type Content42 = string | null;
export type NameNumberOccurrence = string | null;
export type Code43 = string | number | boolean | null;
export type PostBox3 = PostBox;
export type LargeMailUser = LargeMailUserType;
export type PostOffice1 = PostOffice;
export type OtherAttributes61 = {
  [k: string]: string;
};
export type AddressLine17 = AddressLine[];
export type PostOfficeName = PostOfficePostOfficeName[];
export type OtherAttributes62 = {
  [k: string]: string;
};
export type Content43 = string | null;
export type Type43 = string | number | boolean | null;
export type Code44 = string | number | boolean | null;
export type PostOfficeNumber = PostOfficePostOfficeNumber;
export type OtherAttributes63 = {
  [k: string]: string;
};
export type Content44 = string | null;
export type Indicator4 = string | number | boolean | null;
export type IndicatorOccurrence2 = string | null;
export type Code45 = string | number | boolean | null;
export type PostalRoute = PostalRouteType;
export type OtherAttributes64 = {
  [k: string]: string;
};
export type AddressLine18 = AddressLine[];
export type PostalRouteName = [PostalRouteTypePostalRouteName, ...PostalRouteTypePostalRouteName[]];
export type OtherAttributes65 = {
  [k: string]: string;
};
export type Content45 = string | null;
export type Type44 = string | number | boolean | null;
export type Code46 = string | number | boolean | null;
export type PostalRouteNumber = PostalRouteTypePostalRouteNumber;
export type OtherAttributes66 = {
  [k: string]: string;
};
export type Content46 = string | null;
export type Code47 = string | number | boolean | null;
export type PostBox4 = PostBox;
export type Any8 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type45 = string | number | boolean | null;
export type PostBox5 = PostBox;
export type PostalCode4 = PostalCode;
export type Any9 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type46 = string | number | boolean | null;
export type Indicator5 = string | number | boolean | null;
export type PostalRoute1 = PostalRouteType;
export type Thoroughfare1 = Thoroughfare;
export type Premise2 = Premise;
export type OtherAttributes67 = {
  [k: string]: string;
};
export type AddressLine19 = AddressLine[];
export type PremiseName = PremisePremiseName[];
export type OtherAttributes68 = {
  [k: string]: string;
};
export type Content47 = string | null;
export type Type47 = string | number | boolean | null;
export type TypeOccurrence1 = string | null;
export type Code48 = string | number | boolean | null;
export type PremiseLocation = PremisePremiseLocation;
export type OtherAttributes69 = {
  [k: string]: string;
};
export type Content48 = string | null;
export type Code49 = string | number | boolean | null;
export type PremiseNumber1 = [PremiseNumber, ...PremiseNumber[]];
export type OtherAttributes70 = {
  [k: string]: string;
};
export type Content49 = string | null;
export type NumberType1 = string | null;
export type Type48 = string | number | boolean | null;
export type Indicator6 = string | number | boolean | null;
export type IndicatorOccurrence3 = string | null;
export type NumberTypeOccurrence = string | null;
export type Code50 = string | number | boolean | null;
export type PremiseNumberRange = PremisePremiseNumberRange;
export type PremiseNumberRangeFrom = PremisePremiseNumberRangePremiseNumberRangeFrom;
export type AddressLine20 = AddressLine[];
export type PremiseNumberPrefix1 = PremiseNumberPrefix[];
export type OtherAttributes71 = {
  [k: string]: string;
};
export type Value = string | null;
export type NumberPrefixSeparator2 = string | number | boolean | null;
export type Type49 = string | number | boolean | null;
export type Code51 = string | number | boolean | null;
export type PremiseNumber2 = [PremiseNumber, ...PremiseNumber[]];
export type PremiseNumberSuffix1 = PremiseNumberSuffix[];
export type OtherAttributes72 = {
  [k: string]: string;
};
export type Content50 = string | null;
export type NumberSuffixSeparator2 = string | number | boolean | null;
export type Type50 = string | number | boolean | null;
export type Code52 = string | number | boolean | null;
export type PremiseNumberRangeTo = PremisePremiseNumberRangePremiseNumberRangeTo;
export type AddressLine21 = AddressLine[];
export type PremiseNumberPrefix2 = PremiseNumberPrefix[];
export type PremiseNumber3 = [PremiseNumber, ...PremiseNumber[]];
export type PremiseNumberSuffix2 = PremiseNumberSuffix[];
export type RangeType1 = string | number | boolean | null;
export type Indicator7 = string | number | boolean | null;
export type Separator1 = string | number | boolean | null;
export type Type51 = string | number | boolean | null;
export type IndicatorOccurence = string | null;
export type NumberRangeOccurence = string | null;
export type PremiseNumberPrefix3 = PremiseNumberPrefix[];
export type PremiseNumberSuffix3 = PremiseNumberSuffix[];
export type BuildingName1 = BuildingNameType[];
export type SubPremise1 = SubPremiseType[];
export type OtherAttributes73 = {
  [k: string]: string;
};
export type AddressLine22 = AddressLine[];
export type SubPremiseName = SubPremiseTypeSubPremiseName[];
export type OtherAttributes74 = {
  [k: string]: string;
};
export type Content51 = string | null;
export type Type52 = string | number | boolean | null;
export type TypeOccurrence2 = string | null;
export type Code53 = string | number | boolean | null;
export type SubPremiseLocation = SubPremiseTypeSubPremiseLocation;
export type Content52 = string | null;
export type Code54 = string | number | boolean | null;
export type SubPremiseNumber = SubPremiseTypeSubPremiseNumber[];
export type OtherAttributes75 = {
  [k: string]: string;
};
export type Content53 = string | null;
export type Indicator8 = string | number | boolean | null;
export type IndicatorOccurrence4 = string | null;
export type NumberTypeOccurrence1 = string | null;
export type PremiseNumberSeparator = string | number | boolean | null;
export type Type53 = string | number | boolean | null;
export type Code55 = string | number | boolean | null;
export type SubPremiseNumberPrefix = SubPremiseTypeSubPremiseNumberPrefix[];
export type OtherAttributes76 = {
  [k: string]: string;
};
export type Content54 = string | null;
export type NumberPrefixSeparator3 = string | number | boolean | null;
export type Type54 = string | number | boolean | null;
export type Code56 = string | number | boolean | null;
export type SubPremiseNumberSuffix = SubPremiseTypeSubPremiseNumberSuffix[];
export type OtherAttributes77 = {
  [k: string]: string;
};
export type Content55 = string | null;
export type NumberSuffixSeparator3 = string | number | boolean | null;
export type Type55 = string | number | boolean | null;
export type Code57 = string | number | boolean | null;
export type BuildingName2 = BuildingNameType[];
export type Firm1 = FirmType;
export type MailStop2 = MailStopType;
export type PostalCode5 = PostalCode;
export type SubPremise = SubPremiseType;
export type Any10 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type56 = string | number | boolean | null;
export type Firm2 = FirmType;
export type MailStop3 = MailStopType;
export type PostalCode6 = PostalCode;
export type Premise1 = Premise;
export type Any11 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type57 = string | number | boolean | null;
export type PremiseDependency = string | number | boolean | null;
export type PremiseDependencyType = string | number | boolean | null;
export type PremiseThoroughfareConnector = string | number | boolean | null;
export type DependentLocality = DependentLocalityType;
export type PostalCode7 = PostalCode;
export type Any12 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type58 = string | number | boolean | null;
export type UsageType = string | number | boolean | null;
export type Connector = string | number | boolean | null;
export type Indicator9 = string | number | boolean | null;
export type Premise3 = Premise;
export type Firm3 = FirmType;
export type PostalCode8 = PostalCode;
export type Any13 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type59 = string | number | boolean | null;
export type DependentThoroughfares = string | null;
export type DependentThoroughfaresIndicator = string | number | boolean | null;
export type DependentThoroughfaresConnector = string | number | boolean | null;
export type DependentThoroughfaresType = string | number | boolean | null;
export type PostalCode9 = PostalCode;
export type Any14 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type60 = string | null;
export type PostOffice2 = PostOffice;
export type PostalRoute2 = PostalRouteType;
export type Thoroughfare3 = Thoroughfare;
export type Premise4 = Premise;
export type DependentLocality2 = DependentLocalityType;
export type PostalCode10 = PostalCode;
export type Any15 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type61 = string | number | boolean | null;
export type UsageType1 = string | number | boolean | null;
export type Indicator10 = string | number | boolean | null;
export type PostOffice3 = PostOffice;
export type PostalCode11 = PostalCode;
export type Any16 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type62 = string | number | boolean | null;
export type UsageType2 = string | number | boolean | null;
export type Indicator11 = string | number | boolean | null;
export type Locality2 = Locality;
export type PostOffice4 = PostOffice;
export type PostalCode12 = PostalCode;
export type Any17 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Type63 = string | number | boolean | null;
export type UsageType3 = string | number | boolean | null;
export type Indicator12 = string | number | boolean | null;
export type Locality3 = Locality;
export type Thoroughfare4 = Thoroughfare;
export type Any18 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type AdministrativeArea2 = AdministrativeArea;
export type Locality4 = Locality;
export type Thoroughfare5 = Thoroughfare;
export type Any19 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type AddressType = string | number | boolean | null;
export type CurrentStatus = string | number | boolean | null;
export type ValidFromDate = string | number | boolean | null;
export type ValidToDate = string | number | boolean | null;
export type Usage = string | number | boolean | null;
export type AddressDetailsKey = string | number | boolean | null;
export type Code58 = string | number | boolean | null;
export type OtherAttributes78 = {
  [k: string]: string;
};
export type AddressDetails1 = [AddressDetails, ...AddressDetails[]];
export type Any20 = {
  /**
   * http://www.w3.org/TR/xmlschema-2/#QName
   */
  name?: {
    namespaceURI?: (string | null) | "";
    /**
     * http://www.w3.org/TR/xmlschema-2/#NCName
     */
    localPart: string | null;
    prefix?: (string | null) | "";
    [k: string]: unknown;
  } | null;
  value?: unknown;
  [k: string]: unknown;
}[];
export type Version = string | number | boolean | null;

export interface AddressDetails {
  otherAttributes?: OtherAttributes;
  postalServiceElements?: PostalServiceElements;
  address: Address;
  addressLines: AddressLines;
  country: Country;
  administrativeArea: AdministrativeArea2;
  locality: Locality4;
  thoroughfare: Thoroughfare5;
  any?: Any19;
  addressType?: AddressType;
  currentStatus?: CurrentStatus;
  validFromDate?: ValidFromDate;
  validToDate?: ValidToDate;
  usage?: Usage;
  addressDetailsKey?: AddressDetailsKey;
  code?: Code58;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElements {
  otherAttributes?: OtherAttributes1;
  addressIdentifier?: AddressIdentifier;
  endorsementLineCode?: EndorsementLineCode;
  keyLineCode?: KeyLineCode;
  barcode?: Barcode;
  sortingCode?: SortingCode;
  addressLatitude?: AddressLatitude;
  addressLatitudeDirection?: AddressLatitudeDirection;
  addressLongitude?: AddressLongitude;
  addressLongitudeDirection?: AddressLongitudeDirection;
  supplementaryPostalServiceData?: SupplementaryPostalServiceData;
  any?: Any;
  type?: Type10;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsAddressIdentifier {
  otherAttributes?: OtherAttributes2;
  content?: Content;
  identifierType?: IdentifierType;
  type?: Type;
  code?: Code;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsEndorsementLineCode {
  otherAttributes?: OtherAttributes3;
  content?: Content1;
  type?: Type1;
  code?: Code1;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsKeyLineCode {
  otherAttributes?: OtherAttributes4;
  content?: Content2;
  type?: Type2;
  code?: Code2;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsBarcode {
  otherAttributes?: OtherAttributes5;
  content?: Content3;
  type?: Type3;
  code?: Code3;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsSortingCode {
  type?: Type4;
  code?: Code4;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsAddressLatitude {
  otherAttributes?: OtherAttributes6;
  content?: Content4;
  type?: Type5;
  code?: Code5;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsAddressLatitudeDirection {
  otherAttributes?: OtherAttributes7;
  content?: Content5;
  type?: Type6;
  code?: Code6;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsAddressLongitude {
  otherAttributes?: OtherAttributes8;
  content?: Content6;
  type?: Type7;
  code?: Code7;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsAddressLongitudeDirection {
  otherAttributes?: OtherAttributes9;
  content?: Content7;
  type?: Type8;
  code?: Code8;
  [k: string]: unknown;
}
export interface AddressDetailsPostalServiceElementsSupplementaryPostalServiceData {
  otherAttributes?: OtherAttributes10;
  content?: Content8;
  type?: Type9;
  code?: Code9;
  [k: string]: unknown;
}
export interface AddressDetailsAddress {
  otherAttributes?: OtherAttributes11;
  content?: Content9;
  type?: Type11;
  code?: Code10;
  [k: string]: unknown;
}
export interface AddressLinesType {
  otherAttributes?: OtherAttributes12;
  addressLine: AddressLine1;
  any?: Any1;
  [k: string]: unknown;
}
export interface AddressLine {
  otherAttributes?: OtherAttributes13;
  content?: Content10;
  type?: Type12;
  code?: Code11;
  [k: string]: unknown;
}
export interface AddressDetailsCountry {
  otherAttributes?: OtherAttributes14;
  addressLine?: AddressLine2;
  countryNameCode?: CountryNameCode;
  countryName?: CountryName1;
  administrativeArea: AdministrativeArea1;
  locality: Locality3;
  thoroughfare: Thoroughfare4;
  any?: Any18;
  [k: string]: unknown;
}
export interface AddressDetailsCountryCountryNameCode {
  otherAttributes?: OtherAttributes15;
  content?: Content11;
  scheme?: Scheme;
  code?: Code12;
  [k: string]: unknown;
}
export interface CountryName {
  otherAttributes?: OtherAttributes16;
  content?: Content12;
  type?: Type13;
  code?: Code13;
  [k: string]: unknown;
}
export interface AdministrativeArea {
  otherAttributes?: OtherAttributes17;
  addressLine?: AddressLine3;
  administrativeAreaName?: AdministrativeAreaName;
  subAdministrativeArea?: SubAdministrativeArea;
  locality: Locality2;
  postOffice: PostOffice4;
  postalCode: PostalCode12;
  any?: Any17;
  type?: Type63;
  usageType?: UsageType3;
  indicator?: Indicator12;
  [k: string]: unknown;
}
export interface AdministrativeAreaAdministrativeAreaName {
  otherAttributes?: OtherAttributes18;
  content?: Content13;
  type?: Type14;
  code?: Code14;
  [k: string]: unknown;
}
export interface AdministrativeAreaSubAdministrativeArea {
  otherAttributes?: OtherAttributes19;
  addressLine?: AddressLine4;
  subAdministrativeAreaName?: SubAdministrativeAreaName;
  locality: Locality1;
  postOffice: PostOffice3;
  postalCode: PostalCode11;
  any?: Any16;
  type?: Type62;
  usageType?: UsageType2;
  indicator?: Indicator11;
  [k: string]: unknown;
}
export interface AdministrativeAreaSubAdministrativeAreaSubAdministrativeAreaName {
  otherAttributes?: OtherAttributes20;
  content?: Content14;
  type?: Type15;
  code?: Code15;
  [k: string]: unknown;
}
export interface Locality {
  otherAttributes?: OtherAttributes21;
  addressLine?: AddressLine5;
  localityName?: LocalityName;
  postBox: PostBox1;
  largeMailUser: LargeMailUser1;
  postOffice: PostOffice2;
  postalRoute: PostalRoute2;
  thoroughfare?: Thoroughfare3;
  premise?: Premise4;
  dependentLocality?: DependentLocality2;
  postalCode?: PostalCode10;
  any?: Any15;
  type?: Type61;
  usageType?: UsageType1;
  indicator?: Indicator10;
  [k: string]: unknown;
}
export interface LocalityLocalityName {
  otherAttributes?: OtherAttributes22;
  content?: Content15;
  type?: Type16;
  code?: Code16;
  [k: string]: unknown;
}
export interface PostBox {
  otherAttributes?: OtherAttributes23;
  addressLine?: AddressLine6;
  postBoxNumber: PostBoxNumber;
  postBoxNumberPrefix?: PostBoxNumberPrefix;
  postBoxNumberSuffix?: PostBoxNumberSuffix;
  postBoxNumberExtension?: PostBoxNumberExtension;
  firm?: Firm;
  postalCode?: PostalCode3;
  any?: Any6;
  type?: Type28;
  indicator?: Indicator;
  [k: string]: unknown;
}
export interface PostBoxPostBoxNumber {
  otherAttributes?: OtherAttributes24;
  content?: Content16;
  code?: Code17;
  [k: string]: unknown;
}
export interface PostBoxPostBoxNumberPrefix {
  otherAttributes?: OtherAttributes25;
  content?: Content17;
  numberPrefixSeparator?: NumberPrefixSeparator;
  code?: Code18;
  [k: string]: unknown;
}
export interface PostBoxPostBoxNumberSuffix {
  otherAttributes?: OtherAttributes26;
  content?: Content18;
  numberSuffixSeparator?: NumberSuffixSeparator;
  code?: Code19;
  [k: string]: unknown;
}
export interface PostBoxPostBoxNumberExtension {
  otherAttributes?: OtherAttributes27;
  content?: Content19;
  numberExtensionSeparator?: NumberExtensionSeparator;
  [k: string]: unknown;
}
export interface FirmType {
  otherAttributes?: OtherAttributes28;
  addressLine?: AddressLine7;
  firmName?: FirmName;
  department?: Department1;
  mailStop?: MailStop1;
  postalCode?: PostalCode2;
  any?: Any5;
  type?: Type27;
  [k: string]: unknown;
}
export interface FirmTypeFirmName {
  otherAttributes?: OtherAttributes29;
  content?: Content20;
  type?: Type17;
  code?: Code20;
  [k: string]: unknown;
}
export interface Department {
  otherAttributes?: OtherAttributes30;
  addressLine?: AddressLine8;
  departmentName?: DepartmentName;
  mailStop?: MailStop;
  postalCode?: PostalCode1;
  any?: Any4;
  type?: Type26;
  [k: string]: unknown;
}
export interface DepartmentDepartmentName {
  otherAttributes?: OtherAttributes31;
  content?: Content21;
  type?: Type18;
  code?: Code21;
  [k: string]: unknown;
}
export interface MailStopType {
  otherAttributes?: OtherAttributes32;
  addressLine?: AddressLine9;
  mailStopName?: MailStopName;
  mailStopNumber?: MailStopNumber;
  any?: Any2;
  type?: Type20;
  [k: string]: unknown;
}
export interface MailStopTypeMailStopName {
  otherAttributes?: OtherAttributes33;
  content?: Content22;
  type?: Type19;
  code?: Code22;
  [k: string]: unknown;
}
export interface MailStopTypeMailStopNumber {
  otherAttributes?: OtherAttributes34;
  content?: Content23;
  nameNumberSeparator?: NameNumberSeparator;
  code?: Code23;
  [k: string]: unknown;
}
export interface PostalCode {
  otherAttributes?: OtherAttributes35;
  addressLine?: AddressLine10;
  postalCodeNumber?: PostalCodeNumber;
  postalCodeNumberExtension?: PostalCodeNumberExtension;
  postTown?: PostTown;
  any?: Any3;
  type?: Type25;
  [k: string]: unknown;
}
export interface PostalCodePostalCodeNumber {
  otherAttributes?: OtherAttributes36;
  content?: Content24;
  type?: Type21;
  code?: Code24;
  [k: string]: unknown;
}
export interface PostalCodePostalCodeNumberExtension {
  otherAttributes?: OtherAttributes37;
  content?: Content25;
  type?: Type22;
  numberExtensionSeparator?: NumberExtensionSeparator1;
  code?: Code25;
  [k: string]: unknown;
}
export interface PostalCodePostTown {
  otherAttributes?: OtherAttributes38;
  addressLine?: AddressLine11;
  postTownName?: PostTownName;
  postTownSuffix?: PostTownSuffix;
  type?: Type24;
  [k: string]: unknown;
}
export interface PostalCodePostTownPostTownName {
  otherAttributes?: OtherAttributes39;
  content?: Content26;
  type?: Type23;
  code?: Code26;
  [k: string]: unknown;
}
export interface PostalCodePostTownPostTownSuffix {
  otherAttributes?: OtherAttributes40;
  content?: Content27;
  code?: Code27;
  [k: string]: unknown;
}
export interface LargeMailUserType {
  otherAttributes?: OtherAttributes41;
  addressLine?: AddressLine12;
  largeMailUserName?: LargeMailUserName;
  largeMailUserIdentifier?: LargeMailUserIdentifier;
  buildingName?: BuildingName;
  department?: Department2;
  postBox?: PostBox2;
  thoroughfare?: Thoroughfare2;
  postalCode?: PostalCode9;
  any?: Any14;
  type?: Type60;
  [k: string]: unknown;
}
export interface LargeMailUserTypeLargeMailUserName {
  otherAttributes?: OtherAttributes42;
  content?: Content28;
  type?: Type29;
  code?: Code28;
  [k: string]: unknown;
}
export interface LargeMailUserTypeLargeMailUserIdentifier {
  otherAttributes?: OtherAttributes43;
  content?: Content29;
  type?: Type30;
  indicator?: Indicator1;
  code?: Code29;
  [k: string]: unknown;
}
export interface BuildingNameType {
  otherAttributes?: OtherAttributes44;
  content?: Content30;
  type?: Type31;
  typeOccurrence?: TypeOccurrence;
  code?: Code30;
  [k: string]: unknown;
}
export interface Thoroughfare {
  otherAttributes?: OtherAttributes45;
  addressLine?: AddressLine13;
  thoroughfareNumberOrThoroughfareNumberRange?: ThoroughfareNumberOrThoroughfareNumberRange;
  thoroughfareNumberPrefix?: ThoroughfareNumberPrefix1;
  thoroughfareNumberSuffix?: ThoroughfareNumberSuffix1;
  thoroughfarePreDirection?: ThoroughfarePreDirection;
  thoroughfareLeadingType?: ThoroughfareLeadingType;
  thoroughfareName?: ThoroughfareName;
  thoroughfareTrailingType?: ThoroughfareTrailingType;
  thoroughfarePostDirection?: ThoroughfarePostDirection;
  dependentThoroughfare?: DependentThoroughfare;
  dependentLocality: DependentLocality1;
  premise: Premise3;
  firm: Firm3;
  postalCode: PostalCode8;
  any?: Any13;
  type?: Type59;
  dependentThoroughfares?: DependentThoroughfares;
  dependentThoroughfaresIndicator?: DependentThoroughfaresIndicator;
  dependentThoroughfaresConnector?: DependentThoroughfaresConnector;
  dependentThoroughfaresType?: DependentThoroughfaresType;
  [k: string]: unknown;
}
export interface ThoroughfareNumber {
  otherAttributes?: OtherAttributes46;
  content?: Content31;
  numberType?: NumberType;
  type?: Type32;
  indicator?: Indicator2;
  indicatorOccurrence?: IndicatorOccurrence;
  numberOccurrence?: NumberOccurrence;
  code?: Code31;
  [k: string]: unknown;
}
export interface ThoroughfareThoroughfareNumberRange {
  otherAttributes?: OtherAttributes47;
  addressLine?: AddressLine14;
  thoroughfareNumberFrom: ThoroughfareNumberFrom;
  thoroughfareNumberTo: ThoroughfareNumberTo;
  rangeType?: RangeType;
  indicator?: Indicator3;
  separator?: Separator;
  indicatorOccurrence?: IndicatorOccurrence1;
  numberRangeOccurrence?: NumberRangeOccurrence;
  type?: Type35;
  code?: Code36;
  [k: string]: unknown;
}
export interface ThoroughfareThoroughfareNumberRangeThoroughfareNumberFrom {
  otherAttributes?: OtherAttributes48;
  content?: Content34;
  code?: Code34;
  [k: string]: unknown;
}
export interface ThoroughfareNumberSuffix {
  otherAttributes?: OtherAttributes49;
  content?: Content32;
  numberSuffixSeparator?: NumberSuffixSeparator1;
  type?: Type33;
  code?: Code32;
  [k: string]: unknown;
}
export interface ThoroughfareNumberPrefix {
  otherAttributes?: OtherAttributes50;
  content?: Content33;
  numberPrefixSeparator?: NumberPrefixSeparator1;
  type?: Type34;
  code?: Code33;
  [k: string]: unknown;
}
export interface ThoroughfareThoroughfareNumberRangeThoroughfareNumberTo {
  otherAttributes?: OtherAttributes51;
  content?: Content35;
  code?: Code35;
  [k: string]: unknown;
}
export interface ThoroughfarePreDirectionType {
  otherAttributes?: OtherAttributes52;
  content?: Content36;
  type?: Type36;
  code?: Code37;
  [k: string]: unknown;
}
export interface ThoroughfareLeadingTypeType {
  otherAttributes?: OtherAttributes53;
  content?: Content37;
  type?: Type37;
  code?: Code38;
  [k: string]: unknown;
}
export interface ThoroughfareNameType {
  otherAttributes?: OtherAttributes54;
  content?: Content38;
  type?: Type38;
  code?: Code39;
  [k: string]: unknown;
}
export interface ThoroughfareTrailingTypeType {
  otherAttributes?: OtherAttributes55;
  content?: Content39;
  type?: Type39;
  code?: Code40;
  [k: string]: unknown;
}
export interface ThoroughfarePostDirectionType {
  otherAttributes?: OtherAttributes56;
  content?: Content40;
  type?: Type40;
  code?: Code41;
  [k: string]: unknown;
}
export interface ThoroughfareDependentThoroughfare {
  otherAttributes?: OtherAttributes57;
  addressLine?: AddressLine15;
  thoroughfarePreDirection?: ThoroughfarePreDirection1;
  thoroughfareLeadingType?: ThoroughfareLeadingType1;
  thoroughfareName?: ThoroughfareName1;
  thoroughfareTrailingType?: ThoroughfareTrailingType1;
  thoroughfarePostDirection?: ThoroughfarePostDirection1;
  any?: Any7;
  type?: Type41;
  [k: string]: unknown;
}
export interface DependentLocalityType {
  otherAttributes?: OtherAttributes58;
  addressLine?: AddressLine16;
  dependentLocalityName?: DependentLocalityName;
  dependentLocalityNumber?: DependentLocalityNumber;
  postBox: PostBox3;
  largeMailUser: LargeMailUser;
  postOffice: PostOffice1;
  postalRoute: PostalRoute1;
  thoroughfare?: Thoroughfare1;
  premise?: Premise2;
  dependentLocality?: DependentLocality;
  postalCode?: PostalCode7;
  any?: Any12;
  type?: Type58;
  usageType?: UsageType;
  connector?: Connector;
  indicator?: Indicator9;
  [k: string]: unknown;
}
export interface DependentLocalityTypeDependentLocalityName {
  otherAttributes?: OtherAttributes59;
  content?: Content41;
  type?: Type42;
  code?: Code42;
  [k: string]: unknown;
}
export interface DependentLocalityTypeDependentLocalityNumber {
  otherAttributes?: OtherAttributes60;
  content?: Content42;
  nameNumberOccurrence?: NameNumberOccurrence;
  code?: Code43;
  [k: string]: unknown;
}
export interface PostOffice {
  otherAttributes?: OtherAttributes61;
  addressLine?: AddressLine17;
  postOfficeName?: PostOfficeName;
  postOfficeNumber?: PostOfficeNumber;
  postalRoute?: PostalRoute;
  postBox?: PostBox5;
  postalCode?: PostalCode4;
  any?: Any9;
  type?: Type46;
  indicator?: Indicator5;
  [k: string]: unknown;
}
export interface PostOfficePostOfficeName {
  otherAttributes?: OtherAttributes62;
  content?: Content43;
  type?: Type43;
  code?: Code44;
  [k: string]: unknown;
}
export interface PostOfficePostOfficeNumber {
  otherAttributes?: OtherAttributes63;
  content?: Content44;
  indicator?: Indicator4;
  indicatorOccurrence?: IndicatorOccurrence2;
  code?: Code45;
  [k: string]: unknown;
}
export interface PostalRouteType {
  otherAttributes?: OtherAttributes64;
  addressLine?: AddressLine18;
  postalRouteName: PostalRouteName;
  postalRouteNumber: PostalRouteNumber;
  postBox?: PostBox4;
  any?: Any8;
  type?: Type45;
  [k: string]: unknown;
}
export interface PostalRouteTypePostalRouteName {
  otherAttributes?: OtherAttributes65;
  content?: Content45;
  type?: Type44;
  code?: Code46;
  [k: string]: unknown;
}
export interface PostalRouteTypePostalRouteNumber {
  otherAttributes?: OtherAttributes66;
  content?: Content46;
  code?: Code47;
  [k: string]: unknown;
}
export interface Premise {
  otherAttributes?: OtherAttributes67;
  addressLine?: AddressLine19;
  premiseName?: PremiseName;
  premiseLocation: PremiseLocation;
  premiseNumber: PremiseNumber1;
  premiseNumberRange: PremiseNumberRange;
  premiseNumberPrefix?: PremiseNumberPrefix3;
  premiseNumberSuffix?: PremiseNumberSuffix3;
  buildingName?: BuildingName1;
  subPremise?: SubPremise1;
  firm?: Firm2;
  mailStop?: MailStop3;
  postalCode?: PostalCode6;
  premise?: Premise1;
  any?: Any11;
  type?: Type57;
  premiseDependency?: PremiseDependency;
  premiseDependencyType?: PremiseDependencyType;
  premiseThoroughfareConnector?: PremiseThoroughfareConnector;
  [k: string]: unknown;
}
export interface PremisePremiseName {
  otherAttributes?: OtherAttributes68;
  content?: Content47;
  type?: Type47;
  typeOccurrence?: TypeOccurrence1;
  code?: Code48;
  [k: string]: unknown;
}
export interface PremisePremiseLocation {
  otherAttributes?: OtherAttributes69;
  content?: Content48;
  code?: Code49;
  [k: string]: unknown;
}
export interface PremiseNumber {
  otherAttributes?: OtherAttributes70;
  content?: Content49;
  numberType?: NumberType1;
  type?: Type48;
  indicator?: Indicator6;
  indicatorOccurrence?: IndicatorOccurrence3;
  numberTypeOccurrence?: NumberTypeOccurrence;
  code?: Code50;
  [k: string]: unknown;
}
export interface PremisePremiseNumberRange {
  premiseNumberRangeFrom: PremiseNumberRangeFrom;
  premiseNumberRangeTo: PremiseNumberRangeTo;
  rangeType?: RangeType1;
  indicator?: Indicator7;
  separator?: Separator1;
  type?: Type51;
  indicatorOccurence?: IndicatorOccurence;
  numberRangeOccurence?: NumberRangeOccurence;
  [k: string]: unknown;
}
export interface PremisePremiseNumberRangePremiseNumberRangeFrom {
  addressLine?: AddressLine20;
  premiseNumberPrefix?: PremiseNumberPrefix1;
  premiseNumber: PremiseNumber2;
  premiseNumberSuffix?: PremiseNumberSuffix1;
  [k: string]: unknown;
}
export interface PremiseNumberPrefix {
  otherAttributes?: OtherAttributes71;
  value?: Value;
  numberPrefixSeparator?: NumberPrefixSeparator2;
  type?: Type49;
  code?: Code51;
  [k: string]: unknown;
}
export interface PremiseNumberSuffix {
  otherAttributes?: OtherAttributes72;
  content?: Content50;
  numberSuffixSeparator?: NumberSuffixSeparator2;
  type?: Type50;
  code?: Code52;
  [k: string]: unknown;
}
export interface PremisePremiseNumberRangePremiseNumberRangeTo {
  addressLine?: AddressLine21;
  premiseNumberPrefix?: PremiseNumberPrefix2;
  premiseNumber: PremiseNumber3;
  premiseNumberSuffix?: PremiseNumberSuffix2;
  [k: string]: unknown;
}
export interface SubPremiseType {
  otherAttributes?: OtherAttributes73;
  addressLine?: AddressLine22;
  subPremiseName?: SubPremiseName;
  subPremiseLocation: SubPremiseLocation;
  subPremiseNumber?: SubPremiseNumber;
  subPremiseNumberPrefix?: SubPremiseNumberPrefix;
  subPremiseNumberSuffix?: SubPremiseNumberSuffix;
  buildingName?: BuildingName2;
  firm?: Firm1;
  mailStop?: MailStop2;
  postalCode?: PostalCode5;
  subPremise?: SubPremise;
  any?: Any10;
  type?: Type56;
  [k: string]: unknown;
}
export interface SubPremiseTypeSubPremiseName {
  otherAttributes?: OtherAttributes74;
  content?: Content51;
  type?: Type52;
  typeOccurrence?: TypeOccurrence2;
  code?: Code53;
  [k: string]: unknown;
}
export interface SubPremiseTypeSubPremiseLocation {
  content?: Content52;
  code?: Code54;
  [k: string]: unknown;
}
export interface SubPremiseTypeSubPremiseNumber {
  otherAttributes?: OtherAttributes75;
  content?: Content53;
  indicator?: Indicator8;
  indicatorOccurrence?: IndicatorOccurrence4;
  numberTypeOccurrence?: NumberTypeOccurrence1;
  premiseNumberSeparator?: PremiseNumberSeparator;
  type?: Type53;
  code?: Code55;
  [k: string]: unknown;
}
export interface SubPremiseTypeSubPremiseNumberPrefix {
  otherAttributes?: OtherAttributes76;
  content?: Content54;
  numberPrefixSeparator?: NumberPrefixSeparator3;
  type?: Type54;
  code?: Code56;
  [k: string]: unknown;
}
export interface SubPremiseTypeSubPremiseNumberSuffix {
  otherAttributes?: OtherAttributes77;
  content?: Content55;
  numberSuffixSeparator?: NumberSuffixSeparator3;
  type?: Type55;
  code?: Code57;
  [k: string]: unknown;
}
export interface XAL {
  otherAttributes?: OtherAttributes78;
  addressDetails: AddressDetails1;
  any?: Any20;
  version?: Version;
  [k: string]: unknown;
}
