# This workflow will do a clean install of node dependencies, test and build the source code.
name: Test and Build CI

on:
  push:
    branches-ignore:
      # run on all branches other then main
      - main
    tags-ignore:
      # And do not run for any tags
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - uses: ./.github/actions/test
      - uses: ./.github/actions/build
