# This workflow will do a clean install of node dependencies, test and build the source code.
name: Test and Build CI

on:
  push:
    branches-ignore:
      # run on all branches other then master
      - master
    tags-ignore:
      # And do not run for any tags
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - uses: ./.github/actions/test
      - uses: ./.github/actions/build
